/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gade.gps.strava.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.gade.gps.strava.client.model.ActivityTotal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * A set of rolled-up statistics and totals for an athlete
 */
@JsonPropertyOrder({
  ActivityStats.JSON_PROPERTY_BIGGEST_RIDE_DISTANCE,
  ActivityStats.JSON_PROPERTY_BIGGEST_CLIMB_ELEVATION_GAIN,
  ActivityStats.JSON_PROPERTY_RECENT_RIDE_TOTALS,
  ActivityStats.JSON_PROPERTY_RECENT_RUN_TOTALS,
  ActivityStats.JSON_PROPERTY_RECENT_SWIM_TOTALS,
  ActivityStats.JSON_PROPERTY_YTD_RIDE_TOTALS,
  ActivityStats.JSON_PROPERTY_YTD_RUN_TOTALS,
  ActivityStats.JSON_PROPERTY_YTD_SWIM_TOTALS,
  ActivityStats.JSON_PROPERTY_ALL_RIDE_TOTALS,
  ActivityStats.JSON_PROPERTY_ALL_RUN_TOTALS,
  ActivityStats.JSON_PROPERTY_ALL_SWIM_TOTALS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class ActivityStats {
  public static final String JSON_PROPERTY_BIGGEST_RIDE_DISTANCE = "biggest_ride_distance";
  @jakarta.annotation.Nullable
  private Double biggestRideDistance;

  public static final String JSON_PROPERTY_BIGGEST_CLIMB_ELEVATION_GAIN = "biggest_climb_elevation_gain";
  @jakarta.annotation.Nullable
  private Double biggestClimbElevationGain;

  public static final String JSON_PROPERTY_RECENT_RIDE_TOTALS = "recent_ride_totals";
  @jakarta.annotation.Nullable
  private ActivityTotal recentRideTotals;

  public static final String JSON_PROPERTY_RECENT_RUN_TOTALS = "recent_run_totals";
  @jakarta.annotation.Nullable
  private ActivityTotal recentRunTotals;

  public static final String JSON_PROPERTY_RECENT_SWIM_TOTALS = "recent_swim_totals";
  @jakarta.annotation.Nullable
  private ActivityTotal recentSwimTotals;

  public static final String JSON_PROPERTY_YTD_RIDE_TOTALS = "ytd_ride_totals";
  @jakarta.annotation.Nullable
  private ActivityTotal ytdRideTotals;

  public static final String JSON_PROPERTY_YTD_RUN_TOTALS = "ytd_run_totals";
  @jakarta.annotation.Nullable
  private ActivityTotal ytdRunTotals;

  public static final String JSON_PROPERTY_YTD_SWIM_TOTALS = "ytd_swim_totals";
  @jakarta.annotation.Nullable
  private ActivityTotal ytdSwimTotals;

  public static final String JSON_PROPERTY_ALL_RIDE_TOTALS = "all_ride_totals";
  @jakarta.annotation.Nullable
  private ActivityTotal allRideTotals;

  public static final String JSON_PROPERTY_ALL_RUN_TOTALS = "all_run_totals";
  @jakarta.annotation.Nullable
  private ActivityTotal allRunTotals;

  public static final String JSON_PROPERTY_ALL_SWIM_TOTALS = "all_swim_totals";
  @jakarta.annotation.Nullable
  private ActivityTotal allSwimTotals;

  public ActivityStats() {
  }

  public ActivityStats biggestRideDistance(@jakarta.annotation.Nullable Double biggestRideDistance) {
    
    this.biggestRideDistance = biggestRideDistance;
    return this;
  }

  /**
   * The longest distance ridden by the athlete.
   * @return biggestRideDistance
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BIGGEST_RIDE_DISTANCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getBiggestRideDistance() {
    return biggestRideDistance;
  }


  @JsonProperty(value = JSON_PROPERTY_BIGGEST_RIDE_DISTANCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBiggestRideDistance(@jakarta.annotation.Nullable Double biggestRideDistance) {
    this.biggestRideDistance = biggestRideDistance;
  }

  public ActivityStats biggestClimbElevationGain(@jakarta.annotation.Nullable Double biggestClimbElevationGain) {
    
    this.biggestClimbElevationGain = biggestClimbElevationGain;
    return this;
  }

  /**
   * The highest climb ridden by the athlete.
   * @return biggestClimbElevationGain
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BIGGEST_CLIMB_ELEVATION_GAIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getBiggestClimbElevationGain() {
    return biggestClimbElevationGain;
  }


  @JsonProperty(value = JSON_PROPERTY_BIGGEST_CLIMB_ELEVATION_GAIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBiggestClimbElevationGain(@jakarta.annotation.Nullable Double biggestClimbElevationGain) {
    this.biggestClimbElevationGain = biggestClimbElevationGain;
  }

  public ActivityStats recentRideTotals(@jakarta.annotation.Nullable ActivityTotal recentRideTotals) {
    
    this.recentRideTotals = recentRideTotals;
    return this;
  }

  /**
   * Get recentRideTotals
   * @return recentRideTotals
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RECENT_RIDE_TOTALS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ActivityTotal getRecentRideTotals() {
    return recentRideTotals;
  }


  @JsonProperty(value = JSON_PROPERTY_RECENT_RIDE_TOTALS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRecentRideTotals(@jakarta.annotation.Nullable ActivityTotal recentRideTotals) {
    this.recentRideTotals = recentRideTotals;
  }

  public ActivityStats recentRunTotals(@jakarta.annotation.Nullable ActivityTotal recentRunTotals) {
    
    this.recentRunTotals = recentRunTotals;
    return this;
  }

  /**
   * Get recentRunTotals
   * @return recentRunTotals
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RECENT_RUN_TOTALS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ActivityTotal getRecentRunTotals() {
    return recentRunTotals;
  }


  @JsonProperty(value = JSON_PROPERTY_RECENT_RUN_TOTALS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRecentRunTotals(@jakarta.annotation.Nullable ActivityTotal recentRunTotals) {
    this.recentRunTotals = recentRunTotals;
  }

  public ActivityStats recentSwimTotals(@jakarta.annotation.Nullable ActivityTotal recentSwimTotals) {
    
    this.recentSwimTotals = recentSwimTotals;
    return this;
  }

  /**
   * Get recentSwimTotals
   * @return recentSwimTotals
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RECENT_SWIM_TOTALS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ActivityTotal getRecentSwimTotals() {
    return recentSwimTotals;
  }


  @JsonProperty(value = JSON_PROPERTY_RECENT_SWIM_TOTALS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRecentSwimTotals(@jakarta.annotation.Nullable ActivityTotal recentSwimTotals) {
    this.recentSwimTotals = recentSwimTotals;
  }

  public ActivityStats ytdRideTotals(@jakarta.annotation.Nullable ActivityTotal ytdRideTotals) {
    
    this.ytdRideTotals = ytdRideTotals;
    return this;
  }

  /**
   * Get ytdRideTotals
   * @return ytdRideTotals
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_YTD_RIDE_TOTALS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ActivityTotal getYtdRideTotals() {
    return ytdRideTotals;
  }


  @JsonProperty(value = JSON_PROPERTY_YTD_RIDE_TOTALS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setYtdRideTotals(@jakarta.annotation.Nullable ActivityTotal ytdRideTotals) {
    this.ytdRideTotals = ytdRideTotals;
  }

  public ActivityStats ytdRunTotals(@jakarta.annotation.Nullable ActivityTotal ytdRunTotals) {
    
    this.ytdRunTotals = ytdRunTotals;
    return this;
  }

  /**
   * Get ytdRunTotals
   * @return ytdRunTotals
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_YTD_RUN_TOTALS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ActivityTotal getYtdRunTotals() {
    return ytdRunTotals;
  }


  @JsonProperty(value = JSON_PROPERTY_YTD_RUN_TOTALS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setYtdRunTotals(@jakarta.annotation.Nullable ActivityTotal ytdRunTotals) {
    this.ytdRunTotals = ytdRunTotals;
  }

  public ActivityStats ytdSwimTotals(@jakarta.annotation.Nullable ActivityTotal ytdSwimTotals) {
    
    this.ytdSwimTotals = ytdSwimTotals;
    return this;
  }

  /**
   * Get ytdSwimTotals
   * @return ytdSwimTotals
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_YTD_SWIM_TOTALS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ActivityTotal getYtdSwimTotals() {
    return ytdSwimTotals;
  }


  @JsonProperty(value = JSON_PROPERTY_YTD_SWIM_TOTALS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setYtdSwimTotals(@jakarta.annotation.Nullable ActivityTotal ytdSwimTotals) {
    this.ytdSwimTotals = ytdSwimTotals;
  }

  public ActivityStats allRideTotals(@jakarta.annotation.Nullable ActivityTotal allRideTotals) {
    
    this.allRideTotals = allRideTotals;
    return this;
  }

  /**
   * Get allRideTotals
   * @return allRideTotals
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ALL_RIDE_TOTALS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ActivityTotal getAllRideTotals() {
    return allRideTotals;
  }


  @JsonProperty(value = JSON_PROPERTY_ALL_RIDE_TOTALS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAllRideTotals(@jakarta.annotation.Nullable ActivityTotal allRideTotals) {
    this.allRideTotals = allRideTotals;
  }

  public ActivityStats allRunTotals(@jakarta.annotation.Nullable ActivityTotal allRunTotals) {
    
    this.allRunTotals = allRunTotals;
    return this;
  }

  /**
   * Get allRunTotals
   * @return allRunTotals
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ALL_RUN_TOTALS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ActivityTotal getAllRunTotals() {
    return allRunTotals;
  }


  @JsonProperty(value = JSON_PROPERTY_ALL_RUN_TOTALS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAllRunTotals(@jakarta.annotation.Nullable ActivityTotal allRunTotals) {
    this.allRunTotals = allRunTotals;
  }

  public ActivityStats allSwimTotals(@jakarta.annotation.Nullable ActivityTotal allSwimTotals) {
    
    this.allSwimTotals = allSwimTotals;
    return this;
  }

  /**
   * Get allSwimTotals
   * @return allSwimTotals
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ALL_SWIM_TOTALS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ActivityTotal getAllSwimTotals() {
    return allSwimTotals;
  }


  @JsonProperty(value = JSON_PROPERTY_ALL_SWIM_TOTALS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAllSwimTotals(@jakarta.annotation.Nullable ActivityTotal allSwimTotals) {
    this.allSwimTotals = allSwimTotals;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActivityStats activityStats = (ActivityStats) o;
    return Objects.equals(this.biggestRideDistance, activityStats.biggestRideDistance) &&
        Objects.equals(this.biggestClimbElevationGain, activityStats.biggestClimbElevationGain) &&
        Objects.equals(this.recentRideTotals, activityStats.recentRideTotals) &&
        Objects.equals(this.recentRunTotals, activityStats.recentRunTotals) &&
        Objects.equals(this.recentSwimTotals, activityStats.recentSwimTotals) &&
        Objects.equals(this.ytdRideTotals, activityStats.ytdRideTotals) &&
        Objects.equals(this.ytdRunTotals, activityStats.ytdRunTotals) &&
        Objects.equals(this.ytdSwimTotals, activityStats.ytdSwimTotals) &&
        Objects.equals(this.allRideTotals, activityStats.allRideTotals) &&
        Objects.equals(this.allRunTotals, activityStats.allRunTotals) &&
        Objects.equals(this.allSwimTotals, activityStats.allSwimTotals);
  }

  @Override
  public int hashCode() {
    return Objects.hash(biggestRideDistance, biggestClimbElevationGain, recentRideTotals, recentRunTotals, recentSwimTotals, ytdRideTotals, ytdRunTotals, ytdSwimTotals, allRideTotals, allRunTotals, allSwimTotals);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActivityStats {\n");
    sb.append("    biggestRideDistance: ").append(toIndentedString(biggestRideDistance)).append("\n");
    sb.append("    biggestClimbElevationGain: ").append(toIndentedString(biggestClimbElevationGain)).append("\n");
    sb.append("    recentRideTotals: ").append(toIndentedString(recentRideTotals)).append("\n");
    sb.append("    recentRunTotals: ").append(toIndentedString(recentRunTotals)).append("\n");
    sb.append("    recentSwimTotals: ").append(toIndentedString(recentSwimTotals)).append("\n");
    sb.append("    ytdRideTotals: ").append(toIndentedString(ytdRideTotals)).append("\n");
    sb.append("    ytdRunTotals: ").append(toIndentedString(ytdRunTotals)).append("\n");
    sb.append("    ytdSwimTotals: ").append(toIndentedString(ytdSwimTotals)).append("\n");
    sb.append("    allRideTotals: ").append(toIndentedString(allRideTotals)).append("\n");
    sb.append("    allRunTotals: ").append(toIndentedString(allRunTotals)).append("\n");
    sb.append("    allSwimTotals: ").append(toIndentedString(allSwimTotals)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `biggest_ride_distance` to the URL query string
    if (getBiggestRideDistance() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sbiggest_ride_distance%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getBiggestRideDistance()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `biggest_climb_elevation_gain` to the URL query string
    if (getBiggestClimbElevationGain() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sbiggest_climb_elevation_gain%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getBiggestClimbElevationGain()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `recent_ride_totals` to the URL query string
    if (getRecentRideTotals() != null) {
      joiner.add(getRecentRideTotals().toUrlQueryString(prefix + "recent_ride_totals" + suffix));
    }

    // add `recent_run_totals` to the URL query string
    if (getRecentRunTotals() != null) {
      joiner.add(getRecentRunTotals().toUrlQueryString(prefix + "recent_run_totals" + suffix));
    }

    // add `recent_swim_totals` to the URL query string
    if (getRecentSwimTotals() != null) {
      joiner.add(getRecentSwimTotals().toUrlQueryString(prefix + "recent_swim_totals" + suffix));
    }

    // add `ytd_ride_totals` to the URL query string
    if (getYtdRideTotals() != null) {
      joiner.add(getYtdRideTotals().toUrlQueryString(prefix + "ytd_ride_totals" + suffix));
    }

    // add `ytd_run_totals` to the URL query string
    if (getYtdRunTotals() != null) {
      joiner.add(getYtdRunTotals().toUrlQueryString(prefix + "ytd_run_totals" + suffix));
    }

    // add `ytd_swim_totals` to the URL query string
    if (getYtdSwimTotals() != null) {
      joiner.add(getYtdSwimTotals().toUrlQueryString(prefix + "ytd_swim_totals" + suffix));
    }

    // add `all_ride_totals` to the URL query string
    if (getAllRideTotals() != null) {
      joiner.add(getAllRideTotals().toUrlQueryString(prefix + "all_ride_totals" + suffix));
    }

    // add `all_run_totals` to the URL query string
    if (getAllRunTotals() != null) {
      joiner.add(getAllRunTotals().toUrlQueryString(prefix + "all_run_totals" + suffix));
    }

    // add `all_swim_totals` to the URL query string
    if (getAllSwimTotals() != null) {
      joiner.add(getAllSwimTotals().toUrlQueryString(prefix + "all_swim_totals" + suffix));
    }

    return joiner.toString();
  }

}

