/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gade.gps.strava.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.gade.gps.strava.client.model.TimedZoneRange;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * ActivityZone
 */
@JsonPropertyOrder({
  ActivityZone.JSON_PROPERTY_SCORE,
  ActivityZone.JSON_PROPERTY_DISTRIBUTION_BUCKETS,
  ActivityZone.JSON_PROPERTY_TYPE,
  ActivityZone.JSON_PROPERTY_SENSOR_BASED,
  ActivityZone.JSON_PROPERTY_POINTS,
  ActivityZone.JSON_PROPERTY_CUSTOM_ZONES,
  ActivityZone.JSON_PROPERTY_MAX
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class ActivityZone {
  public static final String JSON_PROPERTY_SCORE = "score";
  @jakarta.annotation.Nullable
  private Integer score;

  public static final String JSON_PROPERTY_DISTRIBUTION_BUCKETS = "distribution_buckets";
  @jakarta.annotation.Nullable
  private List<TimedZoneRange> distributionBuckets = new ArrayList<>();

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    HEARTRATE(String.valueOf("heartrate")),
    
    POWER(String.valueOf("power"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private TypeEnum type;

  public static final String JSON_PROPERTY_SENSOR_BASED = "sensor_based";
  @jakarta.annotation.Nullable
  private Boolean sensorBased;

  public static final String JSON_PROPERTY_POINTS = "points";
  @jakarta.annotation.Nullable
  private Integer points;

  public static final String JSON_PROPERTY_CUSTOM_ZONES = "custom_zones";
  @jakarta.annotation.Nullable
  private Boolean customZones;

  public static final String JSON_PROPERTY_MAX = "max";
  @jakarta.annotation.Nullable
  private Integer max;

  public ActivityZone() {
  }

  public ActivityZone score(@jakarta.annotation.Nullable Integer score) {
    
    this.score = score;
    return this;
  }

  /**
   * Get score
   * @return score
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCORE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getScore() {
    return score;
  }


  @JsonProperty(value = JSON_PROPERTY_SCORE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScore(@jakarta.annotation.Nullable Integer score) {
    this.score = score;
  }

  public ActivityZone distributionBuckets(@jakarta.annotation.Nullable List<TimedZoneRange> distributionBuckets) {
    
    this.distributionBuckets = distributionBuckets;
    return this;
  }

  public ActivityZone addDistributionBucketsItem(TimedZoneRange distributionBucketsItem) {
    if (this.distributionBuckets == null) {
      this.distributionBuckets = new ArrayList<>();
    }
    this.distributionBuckets.add(distributionBucketsItem);
    return this;
  }

  /**
   * Stores the exclusive ranges representing zones and the time spent in each.
   * @return distributionBuckets
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DISTRIBUTION_BUCKETS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<TimedZoneRange> getDistributionBuckets() {
    return distributionBuckets;
  }


  @JsonProperty(value = JSON_PROPERTY_DISTRIBUTION_BUCKETS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDistributionBuckets(@jakarta.annotation.Nullable List<TimedZoneRange> distributionBuckets) {
    this.distributionBuckets = distributionBuckets;
  }

  public ActivityZone type(@jakarta.annotation.Nullable TypeEnum type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@jakarta.annotation.Nullable TypeEnum type) {
    this.type = type;
  }

  public ActivityZone sensorBased(@jakarta.annotation.Nullable Boolean sensorBased) {
    
    this.sensorBased = sensorBased;
    return this;
  }

  /**
   * Get sensorBased
   * @return sensorBased
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SENSOR_BASED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSensorBased() {
    return sensorBased;
  }


  @JsonProperty(value = JSON_PROPERTY_SENSOR_BASED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSensorBased(@jakarta.annotation.Nullable Boolean sensorBased) {
    this.sensorBased = sensorBased;
  }

  public ActivityZone points(@jakarta.annotation.Nullable Integer points) {
    
    this.points = points;
    return this;
  }

  /**
   * Get points
   * @return points
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_POINTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPoints() {
    return points;
  }


  @JsonProperty(value = JSON_PROPERTY_POINTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPoints(@jakarta.annotation.Nullable Integer points) {
    this.points = points;
  }

  public ActivityZone customZones(@jakarta.annotation.Nullable Boolean customZones) {
    
    this.customZones = customZones;
    return this;
  }

  /**
   * Get customZones
   * @return customZones
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CUSTOM_ZONES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCustomZones() {
    return customZones;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOM_ZONES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomZones(@jakarta.annotation.Nullable Boolean customZones) {
    this.customZones = customZones;
  }

  public ActivityZone max(@jakarta.annotation.Nullable Integer max) {
    
    this.max = max;
    return this;
  }

  /**
   * Get max
   * @return max
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMax() {
    return max;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMax(@jakarta.annotation.Nullable Integer max) {
    this.max = max;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActivityZone activityZone = (ActivityZone) o;
    return Objects.equals(this.score, activityZone.score) &&
        Objects.equals(this.distributionBuckets, activityZone.distributionBuckets) &&
        Objects.equals(this.type, activityZone.type) &&
        Objects.equals(this.sensorBased, activityZone.sensorBased) &&
        Objects.equals(this.points, activityZone.points) &&
        Objects.equals(this.customZones, activityZone.customZones) &&
        Objects.equals(this.max, activityZone.max);
  }

  @Override
  public int hashCode() {
    return Objects.hash(score, distributionBuckets, type, sensorBased, points, customZones, max);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActivityZone {\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("    distributionBuckets: ").append(toIndentedString(distributionBuckets)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    sensorBased: ").append(toIndentedString(sensorBased)).append("\n");
    sb.append("    points: ").append(toIndentedString(points)).append("\n");
    sb.append("    customZones: ").append(toIndentedString(customZones)).append("\n");
    sb.append("    max: ").append(toIndentedString(max)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `score` to the URL query string
    if (getScore() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sscore%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getScore()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `distribution_buckets` to the URL query string
    if (getDistributionBuckets() != null) {
      for (int i = 0; i < getDistributionBuckets().size(); i++) {
        if (getDistributionBuckets().get(i) != null) {
          joiner.add(getDistributionBuckets().get(i).toUrlQueryString(String.format(Locale.ROOT, "%sdistribution_buckets%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `type` to the URL query string
    if (getType() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%stype%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getType()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `sensor_based` to the URL query string
    if (getSensorBased() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%ssensor_based%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSensorBased()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `points` to the URL query string
    if (getPoints() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%spoints%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPoints()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `custom_zones` to the URL query string
    if (getCustomZones() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%scustom_zones%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCustomZones()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `max` to the URL query string
    if (getMax() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%smax%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMax()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

