/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gade.gps.strava.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.gade.gps.strava.client.model.SummaryClub;
import com.gade.gps.strava.client.model.SummaryGear;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * DetailedAthlete
 */
@JsonPropertyOrder({
  DetailedAthlete.JSON_PROPERTY_ID,
  DetailedAthlete.JSON_PROPERTY_RESOURCE_STATE,
  DetailedAthlete.JSON_PROPERTY_FIRSTNAME,
  DetailedAthlete.JSON_PROPERTY_LASTNAME,
  DetailedAthlete.JSON_PROPERTY_PROFILE_MEDIUM,
  DetailedAthlete.JSON_PROPERTY_PROFILE,
  DetailedAthlete.JSON_PROPERTY_CITY,
  DetailedAthlete.JSON_PROPERTY_STATE,
  DetailedAthlete.JSON_PROPERTY_COUNTRY,
  DetailedAthlete.JSON_PROPERTY_SEX,
  DetailedAthlete.JSON_PROPERTY_PREMIUM,
  DetailedAthlete.JSON_PROPERTY_SUMMIT,
  DetailedAthlete.JSON_PROPERTY_CREATED_AT,
  DetailedAthlete.JSON_PROPERTY_UPDATED_AT,
  DetailedAthlete.JSON_PROPERTY_FOLLOWER_COUNT,
  DetailedAthlete.JSON_PROPERTY_FRIEND_COUNT,
  DetailedAthlete.JSON_PROPERTY_MEASUREMENT_PREFERENCE,
  DetailedAthlete.JSON_PROPERTY_FTP,
  DetailedAthlete.JSON_PROPERTY_WEIGHT,
  DetailedAthlete.JSON_PROPERTY_CLUBS,
  DetailedAthlete.JSON_PROPERTY_BIKES,
  DetailedAthlete.JSON_PROPERTY_SHOES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class DetailedAthlete {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_RESOURCE_STATE = "resource_state";
  @jakarta.annotation.Nullable
  private Integer resourceState;

  public static final String JSON_PROPERTY_FIRSTNAME = "firstname";
  @jakarta.annotation.Nullable
  private String firstname;

  public static final String JSON_PROPERTY_LASTNAME = "lastname";
  @jakarta.annotation.Nullable
  private String lastname;

  public static final String JSON_PROPERTY_PROFILE_MEDIUM = "profile_medium";
  @jakarta.annotation.Nullable
  private String profileMedium;

  public static final String JSON_PROPERTY_PROFILE = "profile";
  @jakarta.annotation.Nullable
  private String profile;

  public static final String JSON_PROPERTY_CITY = "city";
  @jakarta.annotation.Nullable
  private String city;

  public static final String JSON_PROPERTY_STATE = "state";
  @jakarta.annotation.Nullable
  private String state;

  public static final String JSON_PROPERTY_COUNTRY = "country";
  @jakarta.annotation.Nullable
  private String country;

  /**
   * The athlete&#39;s sex.
   */
  public enum SexEnum {
    M(String.valueOf("M")),
    
    F(String.valueOf("F"));

    private String value;

    SexEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SexEnum fromValue(String value) {
      for (SexEnum b : SexEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SEX = "sex";
  @jakarta.annotation.Nullable
  private SexEnum sex;

  public static final String JSON_PROPERTY_PREMIUM = "premium";
  @jakarta.annotation.Nullable
  private Boolean premium;

  public static final String JSON_PROPERTY_SUMMIT = "summit";
  @jakarta.annotation.Nullable
  private Boolean summit;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @jakarta.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  @jakarta.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_FOLLOWER_COUNT = "follower_count";
  @jakarta.annotation.Nullable
  private Integer followerCount;

  public static final String JSON_PROPERTY_FRIEND_COUNT = "friend_count";
  @jakarta.annotation.Nullable
  private Integer friendCount;

  /**
   * The athlete&#39;s preferred unit system.
   */
  public enum MeasurementPreferenceEnum {
    FEET(String.valueOf("feet")),
    
    METERS(String.valueOf("meters"));

    private String value;

    MeasurementPreferenceEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static MeasurementPreferenceEnum fromValue(String value) {
      for (MeasurementPreferenceEnum b : MeasurementPreferenceEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_MEASUREMENT_PREFERENCE = "measurement_preference";
  @jakarta.annotation.Nullable
  private MeasurementPreferenceEnum measurementPreference;

  public static final String JSON_PROPERTY_FTP = "ftp";
  @jakarta.annotation.Nullable
  private Integer ftp;

  public static final String JSON_PROPERTY_WEIGHT = "weight";
  @jakarta.annotation.Nullable
  private Float weight;

  public static final String JSON_PROPERTY_CLUBS = "clubs";
  @jakarta.annotation.Nullable
  private List<SummaryClub> clubs = new ArrayList<>();

  public static final String JSON_PROPERTY_BIKES = "bikes";
  @jakarta.annotation.Nullable
  private List<SummaryGear> bikes = new ArrayList<>();

  public static final String JSON_PROPERTY_SHOES = "shoes";
  @jakarta.annotation.Nullable
  private List<SummaryGear> shoes = new ArrayList<>();

  public DetailedAthlete() {
  }

  public DetailedAthlete id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * The unique identifier of the athlete
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }

  public DetailedAthlete resourceState(@jakarta.annotation.Nullable Integer resourceState) {
    
    this.resourceState = resourceState;
    return this;
  }

  /**
   * Resource state, indicates level of detail. Possible values: 1 -&gt; \&quot;meta\&quot;, 2 -&gt; \&quot;summary\&quot;, 3 -&gt; \&quot;detail\&quot;
   * @return resourceState
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RESOURCE_STATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getResourceState() {
    return resourceState;
  }


  @JsonProperty(value = JSON_PROPERTY_RESOURCE_STATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResourceState(@jakarta.annotation.Nullable Integer resourceState) {
    this.resourceState = resourceState;
  }

  public DetailedAthlete firstname(@jakarta.annotation.Nullable String firstname) {
    
    this.firstname = firstname;
    return this;
  }

  /**
   * The athlete&#39;s first name.
   * @return firstname
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FIRSTNAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFirstname() {
    return firstname;
  }


  @JsonProperty(value = JSON_PROPERTY_FIRSTNAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFirstname(@jakarta.annotation.Nullable String firstname) {
    this.firstname = firstname;
  }

  public DetailedAthlete lastname(@jakarta.annotation.Nullable String lastname) {
    
    this.lastname = lastname;
    return this;
  }

  /**
   * The athlete&#39;s last name.
   * @return lastname
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LASTNAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLastname() {
    return lastname;
  }


  @JsonProperty(value = JSON_PROPERTY_LASTNAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastname(@jakarta.annotation.Nullable String lastname) {
    this.lastname = lastname;
  }

  public DetailedAthlete profileMedium(@jakarta.annotation.Nullable String profileMedium) {
    
    this.profileMedium = profileMedium;
    return this;
  }

  /**
   * URL to a 62x62 pixel profile picture.
   * @return profileMedium
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROFILE_MEDIUM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProfileMedium() {
    return profileMedium;
  }


  @JsonProperty(value = JSON_PROPERTY_PROFILE_MEDIUM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProfileMedium(@jakarta.annotation.Nullable String profileMedium) {
    this.profileMedium = profileMedium;
  }

  public DetailedAthlete profile(@jakarta.annotation.Nullable String profile) {
    
    this.profile = profile;
    return this;
  }

  /**
   * URL to a 124x124 pixel profile picture.
   * @return profile
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROFILE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProfile() {
    return profile;
  }


  @JsonProperty(value = JSON_PROPERTY_PROFILE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProfile(@jakarta.annotation.Nullable String profile) {
    this.profile = profile;
  }

  public DetailedAthlete city(@jakarta.annotation.Nullable String city) {
    
    this.city = city;
    return this;
  }

  /**
   * The athlete&#39;s city.
   * @return city
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCity() {
    return city;
  }


  @JsonProperty(value = JSON_PROPERTY_CITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCity(@jakarta.annotation.Nullable String city) {
    this.city = city;
  }

  public DetailedAthlete state(@jakarta.annotation.Nullable String state) {
    
    this.state = state;
    return this;
  }

  /**
   * The athlete&#39;s state or geographical region.
   * @return state
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getState() {
    return state;
  }


  @JsonProperty(value = JSON_PROPERTY_STATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setState(@jakarta.annotation.Nullable String state) {
    this.state = state;
  }

  public DetailedAthlete country(@jakarta.annotation.Nullable String country) {
    
    this.country = country;
    return this;
  }

  /**
   * The athlete&#39;s country.
   * @return country
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COUNTRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCountry() {
    return country;
  }


  @JsonProperty(value = JSON_PROPERTY_COUNTRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountry(@jakarta.annotation.Nullable String country) {
    this.country = country;
  }

  public DetailedAthlete sex(@jakarta.annotation.Nullable SexEnum sex) {
    
    this.sex = sex;
    return this;
  }

  /**
   * The athlete&#39;s sex.
   * @return sex
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SEX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SexEnum getSex() {
    return sex;
  }


  @JsonProperty(value = JSON_PROPERTY_SEX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSex(@jakarta.annotation.Nullable SexEnum sex) {
    this.sex = sex;
  }

  public DetailedAthlete premium(@jakarta.annotation.Nullable Boolean premium) {
    
    this.premium = premium;
    return this;
  }

  /**
   * Deprecated.  Use summit field instead. Whether the athlete has any Summit subscription.
   * @return premium
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PREMIUM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPremium() {
    return premium;
  }


  @JsonProperty(value = JSON_PROPERTY_PREMIUM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPremium(@jakarta.annotation.Nullable Boolean premium) {
    this.premium = premium;
  }

  public DetailedAthlete summit(@jakarta.annotation.Nullable Boolean summit) {
    
    this.summit = summit;
    return this;
  }

  /**
   * Whether the athlete has any Summit subscription.
   * @return summit
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUMMIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSummit() {
    return summit;
  }


  @JsonProperty(value = JSON_PROPERTY_SUMMIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSummit(@jakarta.annotation.Nullable Boolean summit) {
    this.summit = summit;
  }

  public DetailedAthlete createdAt(@jakarta.annotation.Nullable OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * The time at which the athlete was created.
   * @return createdAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@jakarta.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public DetailedAthlete updatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * The time at which the athlete was last updated.
   * @return updatedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public DetailedAthlete followerCount(@jakarta.annotation.Nullable Integer followerCount) {
    
    this.followerCount = followerCount;
    return this;
  }

  /**
   * The athlete&#39;s follower count.
   * @return followerCount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FOLLOWER_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFollowerCount() {
    return followerCount;
  }


  @JsonProperty(value = JSON_PROPERTY_FOLLOWER_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFollowerCount(@jakarta.annotation.Nullable Integer followerCount) {
    this.followerCount = followerCount;
  }

  public DetailedAthlete friendCount(@jakarta.annotation.Nullable Integer friendCount) {
    
    this.friendCount = friendCount;
    return this;
  }

  /**
   * The athlete&#39;s friend count.
   * @return friendCount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FRIEND_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFriendCount() {
    return friendCount;
  }


  @JsonProperty(value = JSON_PROPERTY_FRIEND_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFriendCount(@jakarta.annotation.Nullable Integer friendCount) {
    this.friendCount = friendCount;
  }

  public DetailedAthlete measurementPreference(@jakarta.annotation.Nullable MeasurementPreferenceEnum measurementPreference) {
    
    this.measurementPreference = measurementPreference;
    return this;
  }

  /**
   * The athlete&#39;s preferred unit system.
   * @return measurementPreference
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MEASUREMENT_PREFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MeasurementPreferenceEnum getMeasurementPreference() {
    return measurementPreference;
  }


  @JsonProperty(value = JSON_PROPERTY_MEASUREMENT_PREFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMeasurementPreference(@jakarta.annotation.Nullable MeasurementPreferenceEnum measurementPreference) {
    this.measurementPreference = measurementPreference;
  }

  public DetailedAthlete ftp(@jakarta.annotation.Nullable Integer ftp) {
    
    this.ftp = ftp;
    return this;
  }

  /**
   * The athlete&#39;s FTP (Functional Threshold Power).
   * @return ftp
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FTP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFtp() {
    return ftp;
  }


  @JsonProperty(value = JSON_PROPERTY_FTP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFtp(@jakarta.annotation.Nullable Integer ftp) {
    this.ftp = ftp;
  }

  public DetailedAthlete weight(@jakarta.annotation.Nullable Float weight) {
    
    this.weight = weight;
    return this;
  }

  /**
   * The athlete&#39;s weight.
   * @return weight
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WEIGHT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getWeight() {
    return weight;
  }


  @JsonProperty(value = JSON_PROPERTY_WEIGHT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWeight(@jakarta.annotation.Nullable Float weight) {
    this.weight = weight;
  }

  public DetailedAthlete clubs(@jakarta.annotation.Nullable List<SummaryClub> clubs) {
    
    this.clubs = clubs;
    return this;
  }

  public DetailedAthlete addClubsItem(SummaryClub clubsItem) {
    if (this.clubs == null) {
      this.clubs = new ArrayList<>();
    }
    this.clubs.add(clubsItem);
    return this;
  }

  /**
   * The athlete&#39;s clubs.
   * @return clubs
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CLUBS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SummaryClub> getClubs() {
    return clubs;
  }


  @JsonProperty(value = JSON_PROPERTY_CLUBS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClubs(@jakarta.annotation.Nullable List<SummaryClub> clubs) {
    this.clubs = clubs;
  }

  public DetailedAthlete bikes(@jakarta.annotation.Nullable List<SummaryGear> bikes) {
    
    this.bikes = bikes;
    return this;
  }

  public DetailedAthlete addBikesItem(SummaryGear bikesItem) {
    if (this.bikes == null) {
      this.bikes = new ArrayList<>();
    }
    this.bikes.add(bikesItem);
    return this;
  }

  /**
   * The athlete&#39;s bikes.
   * @return bikes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BIKES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SummaryGear> getBikes() {
    return bikes;
  }


  @JsonProperty(value = JSON_PROPERTY_BIKES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBikes(@jakarta.annotation.Nullable List<SummaryGear> bikes) {
    this.bikes = bikes;
  }

  public DetailedAthlete shoes(@jakarta.annotation.Nullable List<SummaryGear> shoes) {
    
    this.shoes = shoes;
    return this;
  }

  public DetailedAthlete addShoesItem(SummaryGear shoesItem) {
    if (this.shoes == null) {
      this.shoes = new ArrayList<>();
    }
    this.shoes.add(shoesItem);
    return this;
  }

  /**
   * The athlete&#39;s shoes.
   * @return shoes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SHOES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SummaryGear> getShoes() {
    return shoes;
  }


  @JsonProperty(value = JSON_PROPERTY_SHOES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShoes(@jakarta.annotation.Nullable List<SummaryGear> shoes) {
    this.shoes = shoes;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DetailedAthlete detailedAthlete = (DetailedAthlete) o;
    return Objects.equals(this.id, detailedAthlete.id) &&
        Objects.equals(this.resourceState, detailedAthlete.resourceState) &&
        Objects.equals(this.firstname, detailedAthlete.firstname) &&
        Objects.equals(this.lastname, detailedAthlete.lastname) &&
        Objects.equals(this.profileMedium, detailedAthlete.profileMedium) &&
        Objects.equals(this.profile, detailedAthlete.profile) &&
        Objects.equals(this.city, detailedAthlete.city) &&
        Objects.equals(this.state, detailedAthlete.state) &&
        Objects.equals(this.country, detailedAthlete.country) &&
        Objects.equals(this.sex, detailedAthlete.sex) &&
        Objects.equals(this.premium, detailedAthlete.premium) &&
        Objects.equals(this.summit, detailedAthlete.summit) &&
        Objects.equals(this.createdAt, detailedAthlete.createdAt) &&
        Objects.equals(this.updatedAt, detailedAthlete.updatedAt) &&
        Objects.equals(this.followerCount, detailedAthlete.followerCount) &&
        Objects.equals(this.friendCount, detailedAthlete.friendCount) &&
        Objects.equals(this.measurementPreference, detailedAthlete.measurementPreference) &&
        Objects.equals(this.ftp, detailedAthlete.ftp) &&
        Objects.equals(this.weight, detailedAthlete.weight) &&
        Objects.equals(this.clubs, detailedAthlete.clubs) &&
        Objects.equals(this.bikes, detailedAthlete.bikes) &&
        Objects.equals(this.shoes, detailedAthlete.shoes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, resourceState, firstname, lastname, profileMedium, profile, city, state, country, sex, premium, summit, createdAt, updatedAt, followerCount, friendCount, measurementPreference, ftp, weight, clubs, bikes, shoes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DetailedAthlete {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    resourceState: ").append(toIndentedString(resourceState)).append("\n");
    sb.append("    firstname: ").append(toIndentedString(firstname)).append("\n");
    sb.append("    lastname: ").append(toIndentedString(lastname)).append("\n");
    sb.append("    profileMedium: ").append(toIndentedString(profileMedium)).append("\n");
    sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    sex: ").append(toIndentedString(sex)).append("\n");
    sb.append("    premium: ").append(toIndentedString(premium)).append("\n");
    sb.append("    summit: ").append(toIndentedString(summit)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    followerCount: ").append(toIndentedString(followerCount)).append("\n");
    sb.append("    friendCount: ").append(toIndentedString(friendCount)).append("\n");
    sb.append("    measurementPreference: ").append(toIndentedString(measurementPreference)).append("\n");
    sb.append("    ftp: ").append(toIndentedString(ftp)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("    clubs: ").append(toIndentedString(clubs)).append("\n");
    sb.append("    bikes: ").append(toIndentedString(bikes)).append("\n");
    sb.append("    shoes: ").append(toIndentedString(shoes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `resource_state` to the URL query string
    if (getResourceState() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sresource_state%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getResourceState()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `firstname` to the URL query string
    if (getFirstname() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sfirstname%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getFirstname()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `lastname` to the URL query string
    if (getLastname() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%slastname%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLastname()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `profile_medium` to the URL query string
    if (getProfileMedium() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sprofile_medium%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getProfileMedium()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `profile` to the URL query string
    if (getProfile() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sprofile%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getProfile()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `city` to the URL query string
    if (getCity() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%scity%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCity()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `state` to the URL query string
    if (getState() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sstate%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getState()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `country` to the URL query string
    if (getCountry() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%scountry%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCountry()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `sex` to the URL query string
    if (getSex() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%ssex%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSex()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `premium` to the URL query string
    if (getPremium() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%spremium%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPremium()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `summit` to the URL query string
    if (getSummit() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%ssummit%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSummit()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `created_at` to the URL query string
    if (getCreatedAt() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%screated_at%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCreatedAt()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `updated_at` to the URL query string
    if (getUpdatedAt() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%supdated_at%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getUpdatedAt()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `follower_count` to the URL query string
    if (getFollowerCount() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sfollower_count%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getFollowerCount()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `friend_count` to the URL query string
    if (getFriendCount() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sfriend_count%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getFriendCount()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `measurement_preference` to the URL query string
    if (getMeasurementPreference() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%smeasurement_preference%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMeasurementPreference()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `ftp` to the URL query string
    if (getFtp() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sftp%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getFtp()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `weight` to the URL query string
    if (getWeight() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sweight%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getWeight()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `clubs` to the URL query string
    if (getClubs() != null) {
      for (int i = 0; i < getClubs().size(); i++) {
        if (getClubs().get(i) != null) {
          joiner.add(getClubs().get(i).toUrlQueryString(String.format(Locale.ROOT, "%sclubs%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `bikes` to the URL query string
    if (getBikes() != null) {
      for (int i = 0; i < getBikes().size(); i++) {
        if (getBikes().get(i) != null) {
          joiner.add(getBikes().get(i).toUrlQueryString(String.format(Locale.ROOT, "%sbikes%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `shoes` to the URL query string
    if (getShoes() != null) {
      for (int i = 0; i < getShoes().size(); i++) {
        if (getShoes().get(i) != null) {
          joiner.add(getShoes().get(i).toUrlQueryString(String.format(Locale.ROOT, "%sshoes%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }

}

