/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gade.gps.strava.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.gade.gps.strava.client.model.MetaActivity;
import com.gade.gps.strava.client.model.MetaAthlete;
import com.gade.gps.strava.client.model.SummarySegment;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * DetailedSegmentEffort
 */
@JsonPropertyOrder({
  DetailedSegmentEffort.JSON_PROPERTY_ID,
  DetailedSegmentEffort.JSON_PROPERTY_ACTIVITY_ID,
  DetailedSegmentEffort.JSON_PROPERTY_ELAPSED_TIME,
  DetailedSegmentEffort.JSON_PROPERTY_START_DATE,
  DetailedSegmentEffort.JSON_PROPERTY_START_DATE_LOCAL,
  DetailedSegmentEffort.JSON_PROPERTY_DISTANCE,
  DetailedSegmentEffort.JSON_PROPERTY_IS_KOM,
  DetailedSegmentEffort.JSON_PROPERTY_NAME,
  DetailedSegmentEffort.JSON_PROPERTY_ACTIVITY,
  DetailedSegmentEffort.JSON_PROPERTY_ATHLETE,
  DetailedSegmentEffort.JSON_PROPERTY_MOVING_TIME,
  DetailedSegmentEffort.JSON_PROPERTY_START_INDEX,
  DetailedSegmentEffort.JSON_PROPERTY_END_INDEX,
  DetailedSegmentEffort.JSON_PROPERTY_AVERAGE_CADENCE,
  DetailedSegmentEffort.JSON_PROPERTY_AVERAGE_WATTS,
  DetailedSegmentEffort.JSON_PROPERTY_DEVICE_WATTS,
  DetailedSegmentEffort.JSON_PROPERTY_AVERAGE_HEARTRATE,
  DetailedSegmentEffort.JSON_PROPERTY_MAX_HEARTRATE,
  DetailedSegmentEffort.JSON_PROPERTY_SEGMENT,
  DetailedSegmentEffort.JSON_PROPERTY_KOM_RANK,
  DetailedSegmentEffort.JSON_PROPERTY_PR_RANK,
  DetailedSegmentEffort.JSON_PROPERTY_HIDDEN
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class DetailedSegmentEffort {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_ACTIVITY_ID = "activity_id";
  @jakarta.annotation.Nullable
  private Long activityId;

  public static final String JSON_PROPERTY_ELAPSED_TIME = "elapsed_time";
  @jakarta.annotation.Nullable
  private Integer elapsedTime;

  public static final String JSON_PROPERTY_START_DATE = "start_date";
  @jakarta.annotation.Nullable
  private OffsetDateTime startDate;

  public static final String JSON_PROPERTY_START_DATE_LOCAL = "start_date_local";
  @jakarta.annotation.Nullable
  private OffsetDateTime startDateLocal;

  public static final String JSON_PROPERTY_DISTANCE = "distance";
  @jakarta.annotation.Nullable
  private Float distance;

  public static final String JSON_PROPERTY_IS_KOM = "is_kom";
  @jakarta.annotation.Nullable
  private Boolean isKom;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_ACTIVITY = "activity";
  @jakarta.annotation.Nullable
  private MetaActivity activity;

  public static final String JSON_PROPERTY_ATHLETE = "athlete";
  @jakarta.annotation.Nullable
  private MetaAthlete athlete;

  public static final String JSON_PROPERTY_MOVING_TIME = "moving_time";
  @jakarta.annotation.Nullable
  private Integer movingTime;

  public static final String JSON_PROPERTY_START_INDEX = "start_index";
  @jakarta.annotation.Nullable
  private Integer startIndex;

  public static final String JSON_PROPERTY_END_INDEX = "end_index";
  @jakarta.annotation.Nullable
  private Integer endIndex;

  public static final String JSON_PROPERTY_AVERAGE_CADENCE = "average_cadence";
  @jakarta.annotation.Nullable
  private Float averageCadence;

  public static final String JSON_PROPERTY_AVERAGE_WATTS = "average_watts";
  @jakarta.annotation.Nullable
  private Float averageWatts;

  public static final String JSON_PROPERTY_DEVICE_WATTS = "device_watts";
  @jakarta.annotation.Nullable
  private Boolean deviceWatts;

  public static final String JSON_PROPERTY_AVERAGE_HEARTRATE = "average_heartrate";
  @jakarta.annotation.Nullable
  private Float averageHeartrate;

  public static final String JSON_PROPERTY_MAX_HEARTRATE = "max_heartrate";
  @jakarta.annotation.Nullable
  private Float maxHeartrate;

  public static final String JSON_PROPERTY_SEGMENT = "segment";
  @jakarta.annotation.Nullable
  private SummarySegment segment;

  public static final String JSON_PROPERTY_KOM_RANK = "kom_rank";
  @jakarta.annotation.Nullable
  private Integer komRank;

  public static final String JSON_PROPERTY_PR_RANK = "pr_rank";
  @jakarta.annotation.Nullable
  private Integer prRank;

  public static final String JSON_PROPERTY_HIDDEN = "hidden";
  @jakarta.annotation.Nullable
  private Boolean hidden;

  public DetailedSegmentEffort() {
  }

  public DetailedSegmentEffort id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * The unique identifier of this effort
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }

  public DetailedSegmentEffort activityId(@jakarta.annotation.Nullable Long activityId) {
    
    this.activityId = activityId;
    return this;
  }

  /**
   * The unique identifier of the activity related to this effort
   * @return activityId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACTIVITY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getActivityId() {
    return activityId;
  }


  @JsonProperty(value = JSON_PROPERTY_ACTIVITY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActivityId(@jakarta.annotation.Nullable Long activityId) {
    this.activityId = activityId;
  }

  public DetailedSegmentEffort elapsedTime(@jakarta.annotation.Nullable Integer elapsedTime) {
    
    this.elapsedTime = elapsedTime;
    return this;
  }

  /**
   * The effort&#39;s elapsed time
   * @return elapsedTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ELAPSED_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getElapsedTime() {
    return elapsedTime;
  }


  @JsonProperty(value = JSON_PROPERTY_ELAPSED_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setElapsedTime(@jakarta.annotation.Nullable Integer elapsedTime) {
    this.elapsedTime = elapsedTime;
  }

  public DetailedSegmentEffort startDate(@jakarta.annotation.Nullable OffsetDateTime startDate) {
    
    this.startDate = startDate;
    return this;
  }

  /**
   * The time at which the effort was started.
   * @return startDate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_START_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getStartDate() {
    return startDate;
  }


  @JsonProperty(value = JSON_PROPERTY_START_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartDate(@jakarta.annotation.Nullable OffsetDateTime startDate) {
    this.startDate = startDate;
  }

  public DetailedSegmentEffort startDateLocal(@jakarta.annotation.Nullable OffsetDateTime startDateLocal) {
    
    this.startDateLocal = startDateLocal;
    return this;
  }

  /**
   * The time at which the effort was started in the local timezone.
   * @return startDateLocal
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_START_DATE_LOCAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getStartDateLocal() {
    return startDateLocal;
  }


  @JsonProperty(value = JSON_PROPERTY_START_DATE_LOCAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartDateLocal(@jakarta.annotation.Nullable OffsetDateTime startDateLocal) {
    this.startDateLocal = startDateLocal;
  }

  public DetailedSegmentEffort distance(@jakarta.annotation.Nullable Float distance) {
    
    this.distance = distance;
    return this;
  }

  /**
   * The effort&#39;s distance in meters
   * @return distance
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DISTANCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getDistance() {
    return distance;
  }


  @JsonProperty(value = JSON_PROPERTY_DISTANCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDistance(@jakarta.annotation.Nullable Float distance) {
    this.distance = distance;
  }

  public DetailedSegmentEffort isKom(@jakarta.annotation.Nullable Boolean isKom) {
    
    this.isKom = isKom;
    return this;
  }

  /**
   * Whether this effort is the current best on the leaderboard
   * @return isKom
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_KOM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsKom() {
    return isKom;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_KOM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsKom(@jakarta.annotation.Nullable Boolean isKom) {
    this.isKom = isKom;
  }

  public DetailedSegmentEffort name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * The name of the segment on which this effort was performed
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public DetailedSegmentEffort activity(@jakarta.annotation.Nullable MetaActivity activity) {
    
    this.activity = activity;
    return this;
  }

  /**
   * Get activity
   * @return activity
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACTIVITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MetaActivity getActivity() {
    return activity;
  }


  @JsonProperty(value = JSON_PROPERTY_ACTIVITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActivity(@jakarta.annotation.Nullable MetaActivity activity) {
    this.activity = activity;
  }

  public DetailedSegmentEffort athlete(@jakarta.annotation.Nullable MetaAthlete athlete) {
    
    this.athlete = athlete;
    return this;
  }

  /**
   * Get athlete
   * @return athlete
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ATHLETE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MetaAthlete getAthlete() {
    return athlete;
  }


  @JsonProperty(value = JSON_PROPERTY_ATHLETE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAthlete(@jakarta.annotation.Nullable MetaAthlete athlete) {
    this.athlete = athlete;
  }

  public DetailedSegmentEffort movingTime(@jakarta.annotation.Nullable Integer movingTime) {
    
    this.movingTime = movingTime;
    return this;
  }

  /**
   * The effort&#39;s moving time
   * @return movingTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MOVING_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMovingTime() {
    return movingTime;
  }


  @JsonProperty(value = JSON_PROPERTY_MOVING_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMovingTime(@jakarta.annotation.Nullable Integer movingTime) {
    this.movingTime = movingTime;
  }

  public DetailedSegmentEffort startIndex(@jakarta.annotation.Nullable Integer startIndex) {
    
    this.startIndex = startIndex;
    return this;
  }

  /**
   * The start index of this effort in its activity&#39;s stream
   * @return startIndex
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_START_INDEX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getStartIndex() {
    return startIndex;
  }


  @JsonProperty(value = JSON_PROPERTY_START_INDEX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartIndex(@jakarta.annotation.Nullable Integer startIndex) {
    this.startIndex = startIndex;
  }

  public DetailedSegmentEffort endIndex(@jakarta.annotation.Nullable Integer endIndex) {
    
    this.endIndex = endIndex;
    return this;
  }

  /**
   * The end index of this effort in its activity&#39;s stream
   * @return endIndex
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_END_INDEX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getEndIndex() {
    return endIndex;
  }


  @JsonProperty(value = JSON_PROPERTY_END_INDEX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndIndex(@jakarta.annotation.Nullable Integer endIndex) {
    this.endIndex = endIndex;
  }

  public DetailedSegmentEffort averageCadence(@jakarta.annotation.Nullable Float averageCadence) {
    
    this.averageCadence = averageCadence;
    return this;
  }

  /**
   * The effort&#39;s average cadence
   * @return averageCadence
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AVERAGE_CADENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getAverageCadence() {
    return averageCadence;
  }


  @JsonProperty(value = JSON_PROPERTY_AVERAGE_CADENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAverageCadence(@jakarta.annotation.Nullable Float averageCadence) {
    this.averageCadence = averageCadence;
  }

  public DetailedSegmentEffort averageWatts(@jakarta.annotation.Nullable Float averageWatts) {
    
    this.averageWatts = averageWatts;
    return this;
  }

  /**
   * The average wattage of this effort
   * @return averageWatts
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AVERAGE_WATTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getAverageWatts() {
    return averageWatts;
  }


  @JsonProperty(value = JSON_PROPERTY_AVERAGE_WATTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAverageWatts(@jakarta.annotation.Nullable Float averageWatts) {
    this.averageWatts = averageWatts;
  }

  public DetailedSegmentEffort deviceWatts(@jakarta.annotation.Nullable Boolean deviceWatts) {
    
    this.deviceWatts = deviceWatts;
    return this;
  }

  /**
   * For riding efforts, whether the wattage was reported by a dedicated recording device
   * @return deviceWatts
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEVICE_WATTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDeviceWatts() {
    return deviceWatts;
  }


  @JsonProperty(value = JSON_PROPERTY_DEVICE_WATTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeviceWatts(@jakarta.annotation.Nullable Boolean deviceWatts) {
    this.deviceWatts = deviceWatts;
  }

  public DetailedSegmentEffort averageHeartrate(@jakarta.annotation.Nullable Float averageHeartrate) {
    
    this.averageHeartrate = averageHeartrate;
    return this;
  }

  /**
   * The heart heart rate of the athlete during this effort
   * @return averageHeartrate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AVERAGE_HEARTRATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getAverageHeartrate() {
    return averageHeartrate;
  }


  @JsonProperty(value = JSON_PROPERTY_AVERAGE_HEARTRATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAverageHeartrate(@jakarta.annotation.Nullable Float averageHeartrate) {
    this.averageHeartrate = averageHeartrate;
  }

  public DetailedSegmentEffort maxHeartrate(@jakarta.annotation.Nullable Float maxHeartrate) {
    
    this.maxHeartrate = maxHeartrate;
    return this;
  }

  /**
   * The maximum heart rate of the athlete during this effort
   * @return maxHeartrate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAX_HEARTRATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getMaxHeartrate() {
    return maxHeartrate;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX_HEARTRATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxHeartrate(@jakarta.annotation.Nullable Float maxHeartrate) {
    this.maxHeartrate = maxHeartrate;
  }

  public DetailedSegmentEffort segment(@jakarta.annotation.Nullable SummarySegment segment) {
    
    this.segment = segment;
    return this;
  }

  /**
   * Get segment
   * @return segment
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SEGMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SummarySegment getSegment() {
    return segment;
  }


  @JsonProperty(value = JSON_PROPERTY_SEGMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSegment(@jakarta.annotation.Nullable SummarySegment segment) {
    this.segment = segment;
  }

  public DetailedSegmentEffort komRank(@jakarta.annotation.Nullable Integer komRank) {
    
    this.komRank = komRank;
    return this;
  }

  /**
   * The rank of the effort on the global leaderboard if it belongs in the top 10 at the time of upload
   * minimum: 1
   * maximum: 10
   * @return komRank
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_KOM_RANK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getKomRank() {
    return komRank;
  }


  @JsonProperty(value = JSON_PROPERTY_KOM_RANK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKomRank(@jakarta.annotation.Nullable Integer komRank) {
    this.komRank = komRank;
  }

  public DetailedSegmentEffort prRank(@jakarta.annotation.Nullable Integer prRank) {
    
    this.prRank = prRank;
    return this;
  }

  /**
   * The rank of the effort on the athlete&#39;s leaderboard if it belongs in the top 3 at the time of upload
   * minimum: 1
   * maximum: 3
   * @return prRank
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PR_RANK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPrRank() {
    return prRank;
  }


  @JsonProperty(value = JSON_PROPERTY_PR_RANK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrRank(@jakarta.annotation.Nullable Integer prRank) {
    this.prRank = prRank;
  }

  public DetailedSegmentEffort hidden(@jakarta.annotation.Nullable Boolean hidden) {
    
    this.hidden = hidden;
    return this;
  }

  /**
   * Whether this effort should be hidden when viewed within an activity
   * @return hidden
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HIDDEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHidden() {
    return hidden;
  }


  @JsonProperty(value = JSON_PROPERTY_HIDDEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHidden(@jakarta.annotation.Nullable Boolean hidden) {
    this.hidden = hidden;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DetailedSegmentEffort detailedSegmentEffort = (DetailedSegmentEffort) o;
    return Objects.equals(this.id, detailedSegmentEffort.id) &&
        Objects.equals(this.activityId, detailedSegmentEffort.activityId) &&
        Objects.equals(this.elapsedTime, detailedSegmentEffort.elapsedTime) &&
        Objects.equals(this.startDate, detailedSegmentEffort.startDate) &&
        Objects.equals(this.startDateLocal, detailedSegmentEffort.startDateLocal) &&
        Objects.equals(this.distance, detailedSegmentEffort.distance) &&
        Objects.equals(this.isKom, detailedSegmentEffort.isKom) &&
        Objects.equals(this.name, detailedSegmentEffort.name) &&
        Objects.equals(this.activity, detailedSegmentEffort.activity) &&
        Objects.equals(this.athlete, detailedSegmentEffort.athlete) &&
        Objects.equals(this.movingTime, detailedSegmentEffort.movingTime) &&
        Objects.equals(this.startIndex, detailedSegmentEffort.startIndex) &&
        Objects.equals(this.endIndex, detailedSegmentEffort.endIndex) &&
        Objects.equals(this.averageCadence, detailedSegmentEffort.averageCadence) &&
        Objects.equals(this.averageWatts, detailedSegmentEffort.averageWatts) &&
        Objects.equals(this.deviceWatts, detailedSegmentEffort.deviceWatts) &&
        Objects.equals(this.averageHeartrate, detailedSegmentEffort.averageHeartrate) &&
        Objects.equals(this.maxHeartrate, detailedSegmentEffort.maxHeartrate) &&
        Objects.equals(this.segment, detailedSegmentEffort.segment) &&
        Objects.equals(this.komRank, detailedSegmentEffort.komRank) &&
        Objects.equals(this.prRank, detailedSegmentEffort.prRank) &&
        Objects.equals(this.hidden, detailedSegmentEffort.hidden);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, activityId, elapsedTime, startDate, startDateLocal, distance, isKom, name, activity, athlete, movingTime, startIndex, endIndex, averageCadence, averageWatts, deviceWatts, averageHeartrate, maxHeartrate, segment, komRank, prRank, hidden);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DetailedSegmentEffort {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    activityId: ").append(toIndentedString(activityId)).append("\n");
    sb.append("    elapsedTime: ").append(toIndentedString(elapsedTime)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    startDateLocal: ").append(toIndentedString(startDateLocal)).append("\n");
    sb.append("    distance: ").append(toIndentedString(distance)).append("\n");
    sb.append("    isKom: ").append(toIndentedString(isKom)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    activity: ").append(toIndentedString(activity)).append("\n");
    sb.append("    athlete: ").append(toIndentedString(athlete)).append("\n");
    sb.append("    movingTime: ").append(toIndentedString(movingTime)).append("\n");
    sb.append("    startIndex: ").append(toIndentedString(startIndex)).append("\n");
    sb.append("    endIndex: ").append(toIndentedString(endIndex)).append("\n");
    sb.append("    averageCadence: ").append(toIndentedString(averageCadence)).append("\n");
    sb.append("    averageWatts: ").append(toIndentedString(averageWatts)).append("\n");
    sb.append("    deviceWatts: ").append(toIndentedString(deviceWatts)).append("\n");
    sb.append("    averageHeartrate: ").append(toIndentedString(averageHeartrate)).append("\n");
    sb.append("    maxHeartrate: ").append(toIndentedString(maxHeartrate)).append("\n");
    sb.append("    segment: ").append(toIndentedString(segment)).append("\n");
    sb.append("    komRank: ").append(toIndentedString(komRank)).append("\n");
    sb.append("    prRank: ").append(toIndentedString(prRank)).append("\n");
    sb.append("    hidden: ").append(toIndentedString(hidden)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `activity_id` to the URL query string
    if (getActivityId() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sactivity_id%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getActivityId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `elapsed_time` to the URL query string
    if (getElapsedTime() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%selapsed_time%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getElapsedTime()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `start_date` to the URL query string
    if (getStartDate() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sstart_date%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getStartDate()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `start_date_local` to the URL query string
    if (getStartDateLocal() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sstart_date_local%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getStartDateLocal()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `distance` to the URL query string
    if (getDistance() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sdistance%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDistance()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `is_kom` to the URL query string
    if (getIsKom() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sis_kom%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getIsKom()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `name` to the URL query string
    if (getName() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sname%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `activity` to the URL query string
    if (getActivity() != null) {
      joiner.add(getActivity().toUrlQueryString(prefix + "activity" + suffix));
    }

    // add `athlete` to the URL query string
    if (getAthlete() != null) {
      joiner.add(getAthlete().toUrlQueryString(prefix + "athlete" + suffix));
    }

    // add `moving_time` to the URL query string
    if (getMovingTime() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%smoving_time%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMovingTime()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `start_index` to the URL query string
    if (getStartIndex() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sstart_index%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getStartIndex()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `end_index` to the URL query string
    if (getEndIndex() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%send_index%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getEndIndex()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `average_cadence` to the URL query string
    if (getAverageCadence() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%saverage_cadence%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAverageCadence()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `average_watts` to the URL query string
    if (getAverageWatts() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%saverage_watts%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAverageWatts()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `device_watts` to the URL query string
    if (getDeviceWatts() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sdevice_watts%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDeviceWatts()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `average_heartrate` to the URL query string
    if (getAverageHeartrate() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%saverage_heartrate%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAverageHeartrate()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `max_heartrate` to the URL query string
    if (getMaxHeartrate() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%smax_heartrate%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMaxHeartrate()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `segment` to the URL query string
    if (getSegment() != null) {
      joiner.add(getSegment().toUrlQueryString(prefix + "segment" + suffix));
    }

    // add `kom_rank` to the URL query string
    if (getKomRank() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%skom_rank%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getKomRank()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `pr_rank` to the URL query string
    if (getPrRank() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%spr_rank%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPrRank()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `hidden` to the URL query string
    if (getHidden() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%shidden%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getHidden()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

