/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gade.gps.strava.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.gade.gps.strava.client.model.ZoneRange;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * HeartRateZoneRanges
 */
@JsonPropertyOrder({
  HeartRateZoneRanges.JSON_PROPERTY_CUSTOM_ZONES,
  HeartRateZoneRanges.JSON_PROPERTY_ZONES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class HeartRateZoneRanges {
  public static final String JSON_PROPERTY_CUSTOM_ZONES = "custom_zones";
  @jakarta.annotation.Nullable
  private Boolean customZones;

  public static final String JSON_PROPERTY_ZONES = "zones";
  @jakarta.annotation.Nullable
  private List<ZoneRange> zones = new ArrayList<>();

  public HeartRateZoneRanges() {
  }

  public HeartRateZoneRanges customZones(@jakarta.annotation.Nullable Boolean customZones) {
    
    this.customZones = customZones;
    return this;
  }

  /**
   * Whether the athlete has set their own custom heart rate zones
   * @return customZones
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CUSTOM_ZONES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCustomZones() {
    return customZones;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOM_ZONES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomZones(@jakarta.annotation.Nullable Boolean customZones) {
    this.customZones = customZones;
  }

  public HeartRateZoneRanges zones(@jakarta.annotation.Nullable List<ZoneRange> zones) {
    
    this.zones = zones;
    return this;
  }

  public HeartRateZoneRanges addZonesItem(ZoneRange zonesItem) {
    if (this.zones == null) {
      this.zones = new ArrayList<>();
    }
    this.zones.add(zonesItem);
    return this;
  }

  /**
   * Get zones
   * @return zones
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ZONES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ZoneRange> getZones() {
    return zones;
  }


  @JsonProperty(value = JSON_PROPERTY_ZONES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setZones(@jakarta.annotation.Nullable List<ZoneRange> zones) {
    this.zones = zones;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HeartRateZoneRanges heartRateZoneRanges = (HeartRateZoneRanges) o;
    return Objects.equals(this.customZones, heartRateZoneRanges.customZones) &&
        Objects.equals(this.zones, heartRateZoneRanges.zones);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customZones, zones);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HeartRateZoneRanges {\n");
    sb.append("    customZones: ").append(toIndentedString(customZones)).append("\n");
    sb.append("    zones: ").append(toIndentedString(zones)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `custom_zones` to the URL query string
    if (getCustomZones() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%scustom_zones%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCustomZones()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `zones` to the URL query string
    if (getZones() != null) {
      for (int i = 0; i < getZones().size(); i++) {
        if (getZones().get(i) != null) {
          joiner.add(getZones().get(i).toUrlQueryString(String.format(Locale.ROOT, "%szones%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }

}

