/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gade.gps.strava.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Locale;

/**
 * An enumeration of the sport types an activity may have. Distinct from ActivityType in that it has new types (e.g. MountainBikeRide)
 */
public enum SportType {
  
  ALPINE_SKI("AlpineSki"),
  
  BACKCOUNTRY_SKI("BackcountrySki"),
  
  BADMINTON("Badminton"),
  
  CANOEING("Canoeing"),
  
  CROSSFIT("Crossfit"),
  
  E_BIKE_RIDE("EBikeRide"),
  
  ELLIPTICAL("Elliptical"),
  
  E_MOUNTAIN_BIKE_RIDE("EMountainBikeRide"),
  
  GOLF("Golf"),
  
  GRAVEL_RIDE("GravelRide"),
  
  HANDCYCLE("Handcycle"),
  
  HIGH_INTENSITY_INTERVAL_TRAINING("HighIntensityIntervalTraining"),
  
  HIKE("Hike"),
  
  ICE_SKATE("IceSkate"),
  
  INLINE_SKATE("InlineSkate"),
  
  KAYAKING("Kayaking"),
  
  KITESURF("Kitesurf"),
  
  MOUNTAIN_BIKE_RIDE("MountainBikeRide"),
  
  NORDIC_SKI("NordicSki"),
  
  PICKLEBALL("Pickleball"),
  
  PILATES("Pilates"),
  
  RACQUETBALL("Racquetball"),
  
  RIDE("Ride"),
  
  ROCK_CLIMBING("RockClimbing"),
  
  ROLLER_SKI("RollerSki"),
  
  ROWING("Rowing"),
  
  RUN("Run"),
  
  SAIL("Sail"),
  
  SKATEBOARD("Skateboard"),
  
  SNOWBOARD("Snowboard"),
  
  SNOWSHOE("Snowshoe"),
  
  SOCCER("Soccer"),
  
  SQUASH("Squash"),
  
  STAIR_STEPPER("StairStepper"),
  
  STAND_UP_PADDLING("StandUpPaddling"),
  
  SURFING("Surfing"),
  
  SWIM("Swim"),
  
  TABLE_TENNIS("TableTennis"),
  
  TENNIS("Tennis"),
  
  TRAIL_RUN("TrailRun"),
  
  VELOMOBILE("Velomobile"),
  
  VIRTUAL_RIDE("VirtualRide"),
  
  VIRTUAL_ROW("VirtualRow"),
  
  VIRTUAL_RUN("VirtualRun"),
  
  WALK("Walk"),
  
  WEIGHT_TRAINING("WeightTraining"),
  
  WHEELCHAIR("Wheelchair"),
  
  WINDSURF("Windsurf"),
  
  WORKOUT("Workout"),
  
  YOGA("Yoga");

  private String value;

  SportType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static SportType fromValue(String value) {
    for (SportType b : SportType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    if (prefix == null) {
      prefix = "";
    }

    return String.format(Locale.ROOT, "%s=%s", prefix, this.toString());
  }
}

