/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gade.gps.strava.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.gade.gps.strava.client.model.ActivityType;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * SummaryClub
 */
@JsonPropertyOrder({
  SummaryClub.JSON_PROPERTY_ID,
  SummaryClub.JSON_PROPERTY_RESOURCE_STATE,
  SummaryClub.JSON_PROPERTY_NAME,
  SummaryClub.JSON_PROPERTY_PROFILE_MEDIUM,
  SummaryClub.JSON_PROPERTY_COVER_PHOTO,
  SummaryClub.JSON_PROPERTY_COVER_PHOTO_SMALL,
  SummaryClub.JSON_PROPERTY_SPORT_TYPE,
  SummaryClub.JSON_PROPERTY_ACTIVITY_TYPES,
  SummaryClub.JSON_PROPERTY_CITY,
  SummaryClub.JSON_PROPERTY_STATE,
  SummaryClub.JSON_PROPERTY_COUNTRY,
  SummaryClub.JSON_PROPERTY_PRIVATE,
  SummaryClub.JSON_PROPERTY_MEMBER_COUNT,
  SummaryClub.JSON_PROPERTY_FEATURED,
  SummaryClub.JSON_PROPERTY_VERIFIED,
  SummaryClub.JSON_PROPERTY_URL
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class SummaryClub {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_RESOURCE_STATE = "resource_state";
  @jakarta.annotation.Nullable
  private Integer resourceState;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_PROFILE_MEDIUM = "profile_medium";
  @jakarta.annotation.Nullable
  private String profileMedium;

  public static final String JSON_PROPERTY_COVER_PHOTO = "cover_photo";
  @jakarta.annotation.Nullable
  private String coverPhoto;

  public static final String JSON_PROPERTY_COVER_PHOTO_SMALL = "cover_photo_small";
  @jakarta.annotation.Nullable
  private String coverPhotoSmall;

  /**
   * Deprecated. Prefer to use activity_types.
   */
  public enum SportTypeEnum {
    CYCLING(String.valueOf("cycling")),
    
    RUNNING(String.valueOf("running")),
    
    TRIATHLON(String.valueOf("triathlon")),
    
    OTHER(String.valueOf("other"));

    private String value;

    SportTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SportTypeEnum fromValue(String value) {
      for (SportTypeEnum b : SportTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SPORT_TYPE = "sport_type";
  @jakarta.annotation.Nullable
  private SportTypeEnum sportType;

  public static final String JSON_PROPERTY_ACTIVITY_TYPES = "activity_types";
  @jakarta.annotation.Nullable
  private List<ActivityType> activityTypes = new ArrayList<>();

  public static final String JSON_PROPERTY_CITY = "city";
  @jakarta.annotation.Nullable
  private String city;

  public static final String JSON_PROPERTY_STATE = "state";
  @jakarta.annotation.Nullable
  private String state;

  public static final String JSON_PROPERTY_COUNTRY = "country";
  @jakarta.annotation.Nullable
  private String country;

  public static final String JSON_PROPERTY_PRIVATE = "private";
  @jakarta.annotation.Nullable
  private Boolean _private;

  public static final String JSON_PROPERTY_MEMBER_COUNT = "member_count";
  @jakarta.annotation.Nullable
  private Integer memberCount;

  public static final String JSON_PROPERTY_FEATURED = "featured";
  @jakarta.annotation.Nullable
  private Boolean featured;

  public static final String JSON_PROPERTY_VERIFIED = "verified";
  @jakarta.annotation.Nullable
  private Boolean verified;

  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nullable
  private String url;

  public SummaryClub() {
  }

  public SummaryClub id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * The club&#39;s unique identifier.
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }

  public SummaryClub resourceState(@jakarta.annotation.Nullable Integer resourceState) {
    
    this.resourceState = resourceState;
    return this;
  }

  /**
   * Resource state, indicates level of detail. Possible values: 1 -&gt; \&quot;meta\&quot;, 2 -&gt; \&quot;summary\&quot;, 3 -&gt; \&quot;detail\&quot;
   * @return resourceState
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RESOURCE_STATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getResourceState() {
    return resourceState;
  }


  @JsonProperty(value = JSON_PROPERTY_RESOURCE_STATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResourceState(@jakarta.annotation.Nullable Integer resourceState) {
    this.resourceState = resourceState;
  }

  public SummaryClub name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * The club&#39;s name.
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public SummaryClub profileMedium(@jakarta.annotation.Nullable String profileMedium) {
    
    this.profileMedium = profileMedium;
    return this;
  }

  /**
   * URL to a 60x60 pixel profile picture.
   * @return profileMedium
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROFILE_MEDIUM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProfileMedium() {
    return profileMedium;
  }


  @JsonProperty(value = JSON_PROPERTY_PROFILE_MEDIUM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProfileMedium(@jakarta.annotation.Nullable String profileMedium) {
    this.profileMedium = profileMedium;
  }

  public SummaryClub coverPhoto(@jakarta.annotation.Nullable String coverPhoto) {
    
    this.coverPhoto = coverPhoto;
    return this;
  }

  /**
   * URL to a ~1185x580 pixel cover photo.
   * @return coverPhoto
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COVER_PHOTO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCoverPhoto() {
    return coverPhoto;
  }


  @JsonProperty(value = JSON_PROPERTY_COVER_PHOTO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCoverPhoto(@jakarta.annotation.Nullable String coverPhoto) {
    this.coverPhoto = coverPhoto;
  }

  public SummaryClub coverPhotoSmall(@jakarta.annotation.Nullable String coverPhotoSmall) {
    
    this.coverPhotoSmall = coverPhotoSmall;
    return this;
  }

  /**
   * URL to a ~360x176  pixel cover photo.
   * @return coverPhotoSmall
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COVER_PHOTO_SMALL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCoverPhotoSmall() {
    return coverPhotoSmall;
  }


  @JsonProperty(value = JSON_PROPERTY_COVER_PHOTO_SMALL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCoverPhotoSmall(@jakarta.annotation.Nullable String coverPhotoSmall) {
    this.coverPhotoSmall = coverPhotoSmall;
  }

  public SummaryClub sportType(@jakarta.annotation.Nullable SportTypeEnum sportType) {
    
    this.sportType = sportType;
    return this;
  }

  /**
   * Deprecated. Prefer to use activity_types.
   * @return sportType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SPORT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SportTypeEnum getSportType() {
    return sportType;
  }


  @JsonProperty(value = JSON_PROPERTY_SPORT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSportType(@jakarta.annotation.Nullable SportTypeEnum sportType) {
    this.sportType = sportType;
  }

  public SummaryClub activityTypes(@jakarta.annotation.Nullable List<ActivityType> activityTypes) {
    
    this.activityTypes = activityTypes;
    return this;
  }

  public SummaryClub addActivityTypesItem(ActivityType activityTypesItem) {
    if (this.activityTypes == null) {
      this.activityTypes = new ArrayList<>();
    }
    this.activityTypes.add(activityTypesItem);
    return this;
  }

  /**
   * The activity types that count for a club. This takes precedence over sport_type.
   * @return activityTypes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACTIVITY_TYPES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ActivityType> getActivityTypes() {
    return activityTypes;
  }


  @JsonProperty(value = JSON_PROPERTY_ACTIVITY_TYPES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActivityTypes(@jakarta.annotation.Nullable List<ActivityType> activityTypes) {
    this.activityTypes = activityTypes;
  }

  public SummaryClub city(@jakarta.annotation.Nullable String city) {
    
    this.city = city;
    return this;
  }

  /**
   * The club&#39;s city.
   * @return city
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCity() {
    return city;
  }


  @JsonProperty(value = JSON_PROPERTY_CITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCity(@jakarta.annotation.Nullable String city) {
    this.city = city;
  }

  public SummaryClub state(@jakarta.annotation.Nullable String state) {
    
    this.state = state;
    return this;
  }

  /**
   * The club&#39;s state or geographical region.
   * @return state
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getState() {
    return state;
  }


  @JsonProperty(value = JSON_PROPERTY_STATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setState(@jakarta.annotation.Nullable String state) {
    this.state = state;
  }

  public SummaryClub country(@jakarta.annotation.Nullable String country) {
    
    this.country = country;
    return this;
  }

  /**
   * The club&#39;s country.
   * @return country
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COUNTRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCountry() {
    return country;
  }


  @JsonProperty(value = JSON_PROPERTY_COUNTRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountry(@jakarta.annotation.Nullable String country) {
    this.country = country;
  }

  public SummaryClub _private(@jakarta.annotation.Nullable Boolean _private) {
    
    this._private = _private;
    return this;
  }

  /**
   * Whether the club is private.
   * @return _private
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRIVATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPrivate() {
    return _private;
  }


  @JsonProperty(value = JSON_PROPERTY_PRIVATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrivate(@jakarta.annotation.Nullable Boolean _private) {
    this._private = _private;
  }

  public SummaryClub memberCount(@jakarta.annotation.Nullable Integer memberCount) {
    
    this.memberCount = memberCount;
    return this;
  }

  /**
   * The club&#39;s member count.
   * @return memberCount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MEMBER_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMemberCount() {
    return memberCount;
  }


  @JsonProperty(value = JSON_PROPERTY_MEMBER_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMemberCount(@jakarta.annotation.Nullable Integer memberCount) {
    this.memberCount = memberCount;
  }

  public SummaryClub featured(@jakarta.annotation.Nullable Boolean featured) {
    
    this.featured = featured;
    return this;
  }

  /**
   * Whether the club is featured or not.
   * @return featured
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FEATURED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getFeatured() {
    return featured;
  }


  @JsonProperty(value = JSON_PROPERTY_FEATURED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFeatured(@jakarta.annotation.Nullable Boolean featured) {
    this.featured = featured;
  }

  public SummaryClub verified(@jakarta.annotation.Nullable Boolean verified) {
    
    this.verified = verified;
    return this;
  }

  /**
   * Whether the club is verified or not.
   * @return verified
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VERIFIED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getVerified() {
    return verified;
  }


  @JsonProperty(value = JSON_PROPERTY_VERIFIED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVerified(@jakarta.annotation.Nullable Boolean verified) {
    this.verified = verified;
  }

  public SummaryClub url(@jakarta.annotation.Nullable String url) {
    
    this.url = url;
    return this;
  }

  /**
   * The club&#39;s vanity URL.
   * @return url
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(value = JSON_PROPERTY_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(@jakarta.annotation.Nullable String url) {
    this.url = url;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SummaryClub summaryClub = (SummaryClub) o;
    return Objects.equals(this.id, summaryClub.id) &&
        Objects.equals(this.resourceState, summaryClub.resourceState) &&
        Objects.equals(this.name, summaryClub.name) &&
        Objects.equals(this.profileMedium, summaryClub.profileMedium) &&
        Objects.equals(this.coverPhoto, summaryClub.coverPhoto) &&
        Objects.equals(this.coverPhotoSmall, summaryClub.coverPhotoSmall) &&
        Objects.equals(this.sportType, summaryClub.sportType) &&
        Objects.equals(this.activityTypes, summaryClub.activityTypes) &&
        Objects.equals(this.city, summaryClub.city) &&
        Objects.equals(this.state, summaryClub.state) &&
        Objects.equals(this.country, summaryClub.country) &&
        Objects.equals(this._private, summaryClub._private) &&
        Objects.equals(this.memberCount, summaryClub.memberCount) &&
        Objects.equals(this.featured, summaryClub.featured) &&
        Objects.equals(this.verified, summaryClub.verified) &&
        Objects.equals(this.url, summaryClub.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, resourceState, name, profileMedium, coverPhoto, coverPhotoSmall, sportType, activityTypes, city, state, country, _private, memberCount, featured, verified, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SummaryClub {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    resourceState: ").append(toIndentedString(resourceState)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    profileMedium: ").append(toIndentedString(profileMedium)).append("\n");
    sb.append("    coverPhoto: ").append(toIndentedString(coverPhoto)).append("\n");
    sb.append("    coverPhotoSmall: ").append(toIndentedString(coverPhotoSmall)).append("\n");
    sb.append("    sportType: ").append(toIndentedString(sportType)).append("\n");
    sb.append("    activityTypes: ").append(toIndentedString(activityTypes)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    _private: ").append(toIndentedString(_private)).append("\n");
    sb.append("    memberCount: ").append(toIndentedString(memberCount)).append("\n");
    sb.append("    featured: ").append(toIndentedString(featured)).append("\n");
    sb.append("    verified: ").append(toIndentedString(verified)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `resource_state` to the URL query string
    if (getResourceState() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sresource_state%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getResourceState()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `name` to the URL query string
    if (getName() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sname%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `profile_medium` to the URL query string
    if (getProfileMedium() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sprofile_medium%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getProfileMedium()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `cover_photo` to the URL query string
    if (getCoverPhoto() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%scover_photo%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCoverPhoto()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `cover_photo_small` to the URL query string
    if (getCoverPhotoSmall() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%scover_photo_small%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCoverPhotoSmall()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `sport_type` to the URL query string
    if (getSportType() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%ssport_type%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSportType()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `activity_types` to the URL query string
    if (getActivityTypes() != null) {
      for (int i = 0; i < getActivityTypes().size(); i++) {
        if (getActivityTypes().get(i) != null) {
          try {
            joiner.add(String.format(Locale.ROOT, "%sactivity_types%s%s=%s", prefix, suffix,
                "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
                URLEncoder.encode(String.valueOf(getActivityTypes().get(i)), "UTF-8").replaceAll("\\+", "%20")));
          } catch (UnsupportedEncodingException e) {
            // Should never happen, UTF-8 is always supported
            throw new RuntimeException(e);
          }
        }
      }
    }

    // add `city` to the URL query string
    if (getCity() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%scity%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCity()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `state` to the URL query string
    if (getState() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sstate%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getState()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `country` to the URL query string
    if (getCountry() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%scountry%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCountry()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `private` to the URL query string
    if (getPrivate() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sprivate%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPrivate()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `member_count` to the URL query string
    if (getMemberCount() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%smember_count%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMemberCount()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `featured` to the URL query string
    if (getFeatured() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sfeatured%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getFeatured()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `verified` to the URL query string
    if (getVerified() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sverified%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getVerified()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `url` to the URL query string
    if (getUrl() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%surl%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getUrl()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

