/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gade.gps.strava.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.gade.gps.strava.client.model.SummaryPRSegmentEffort;
import com.gade.gps.strava.client.model.SummarySegmentEffort;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * SummarySegment
 */
@JsonPropertyOrder({
  SummarySegment.JSON_PROPERTY_ID,
  SummarySegment.JSON_PROPERTY_NAME,
  SummarySegment.JSON_PROPERTY_ACTIVITY_TYPE,
  SummarySegment.JSON_PROPERTY_DISTANCE,
  SummarySegment.JSON_PROPERTY_AVERAGE_GRADE,
  SummarySegment.JSON_PROPERTY_MAXIMUM_GRADE,
  SummarySegment.JSON_PROPERTY_ELEVATION_HIGH,
  SummarySegment.JSON_PROPERTY_ELEVATION_LOW,
  SummarySegment.JSON_PROPERTY_START_LATLNG,
  SummarySegment.JSON_PROPERTY_END_LATLNG,
  SummarySegment.JSON_PROPERTY_CLIMB_CATEGORY,
  SummarySegment.JSON_PROPERTY_CITY,
  SummarySegment.JSON_PROPERTY_STATE,
  SummarySegment.JSON_PROPERTY_COUNTRY,
  SummarySegment.JSON_PROPERTY_PRIVATE,
  SummarySegment.JSON_PROPERTY_ATHLETE_PR_EFFORT,
  SummarySegment.JSON_PROPERTY_ATHLETE_SEGMENT_STATS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class SummarySegment {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  /**
   * Gets or Sets activityType
   */
  public enum ActivityTypeEnum {
    RIDE(String.valueOf("Ride")),
    
    RUN(String.valueOf("Run"));

    private String value;

    ActivityTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ActivityTypeEnum fromValue(String value) {
      for (ActivityTypeEnum b : ActivityTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ACTIVITY_TYPE = "activity_type";
  @jakarta.annotation.Nullable
  private ActivityTypeEnum activityType;

  public static final String JSON_PROPERTY_DISTANCE = "distance";
  @jakarta.annotation.Nullable
  private Float distance;

  public static final String JSON_PROPERTY_AVERAGE_GRADE = "average_grade";
  @jakarta.annotation.Nullable
  private Float averageGrade;

  public static final String JSON_PROPERTY_MAXIMUM_GRADE = "maximum_grade";
  @jakarta.annotation.Nullable
  private Float maximumGrade;

  public static final String JSON_PROPERTY_ELEVATION_HIGH = "elevation_high";
  @jakarta.annotation.Nullable
  private Float elevationHigh;

  public static final String JSON_PROPERTY_ELEVATION_LOW = "elevation_low";
  @jakarta.annotation.Nullable
  private Float elevationLow;

  public static final String JSON_PROPERTY_START_LATLNG = "start_latlng";
  @jakarta.annotation.Nullable
  private List<Float> startLatlng = new ArrayList<>();

  public static final String JSON_PROPERTY_END_LATLNG = "end_latlng";
  @jakarta.annotation.Nullable
  private List<Float> endLatlng = new ArrayList<>();

  public static final String JSON_PROPERTY_CLIMB_CATEGORY = "climb_category";
  @jakarta.annotation.Nullable
  private Integer climbCategory;

  public static final String JSON_PROPERTY_CITY = "city";
  @jakarta.annotation.Nullable
  private String city;

  public static final String JSON_PROPERTY_STATE = "state";
  @jakarta.annotation.Nullable
  private String state;

  public static final String JSON_PROPERTY_COUNTRY = "country";
  @jakarta.annotation.Nullable
  private String country;

  public static final String JSON_PROPERTY_PRIVATE = "private";
  @jakarta.annotation.Nullable
  private Boolean _private;

  public static final String JSON_PROPERTY_ATHLETE_PR_EFFORT = "athlete_pr_effort";
  @jakarta.annotation.Nullable
  private SummaryPRSegmentEffort athletePrEffort;

  public static final String JSON_PROPERTY_ATHLETE_SEGMENT_STATS = "athlete_segment_stats";
  @jakarta.annotation.Nullable
  private SummarySegmentEffort athleteSegmentStats;

  public SummarySegment() {
  }

  public SummarySegment id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * The unique identifier of this segment
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }

  public SummarySegment name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * The name of this segment
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public SummarySegment activityType(@jakarta.annotation.Nullable ActivityTypeEnum activityType) {
    
    this.activityType = activityType;
    return this;
  }

  /**
   * Get activityType
   * @return activityType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACTIVITY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ActivityTypeEnum getActivityType() {
    return activityType;
  }


  @JsonProperty(value = JSON_PROPERTY_ACTIVITY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActivityType(@jakarta.annotation.Nullable ActivityTypeEnum activityType) {
    this.activityType = activityType;
  }

  public SummarySegment distance(@jakarta.annotation.Nullable Float distance) {
    
    this.distance = distance;
    return this;
  }

  /**
   * The segment&#39;s distance, in meters
   * @return distance
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DISTANCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getDistance() {
    return distance;
  }


  @JsonProperty(value = JSON_PROPERTY_DISTANCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDistance(@jakarta.annotation.Nullable Float distance) {
    this.distance = distance;
  }

  public SummarySegment averageGrade(@jakarta.annotation.Nullable Float averageGrade) {
    
    this.averageGrade = averageGrade;
    return this;
  }

  /**
   * The segment&#39;s average grade, in percents
   * @return averageGrade
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AVERAGE_GRADE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getAverageGrade() {
    return averageGrade;
  }


  @JsonProperty(value = JSON_PROPERTY_AVERAGE_GRADE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAverageGrade(@jakarta.annotation.Nullable Float averageGrade) {
    this.averageGrade = averageGrade;
  }

  public SummarySegment maximumGrade(@jakarta.annotation.Nullable Float maximumGrade) {
    
    this.maximumGrade = maximumGrade;
    return this;
  }

  /**
   * The segments&#39;s maximum grade, in percents
   * @return maximumGrade
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAXIMUM_GRADE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getMaximumGrade() {
    return maximumGrade;
  }


  @JsonProperty(value = JSON_PROPERTY_MAXIMUM_GRADE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaximumGrade(@jakarta.annotation.Nullable Float maximumGrade) {
    this.maximumGrade = maximumGrade;
  }

  public SummarySegment elevationHigh(@jakarta.annotation.Nullable Float elevationHigh) {
    
    this.elevationHigh = elevationHigh;
    return this;
  }

  /**
   * The segments&#39;s highest elevation, in meters
   * @return elevationHigh
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ELEVATION_HIGH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getElevationHigh() {
    return elevationHigh;
  }


  @JsonProperty(value = JSON_PROPERTY_ELEVATION_HIGH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setElevationHigh(@jakarta.annotation.Nullable Float elevationHigh) {
    this.elevationHigh = elevationHigh;
  }

  public SummarySegment elevationLow(@jakarta.annotation.Nullable Float elevationLow) {
    
    this.elevationLow = elevationLow;
    return this;
  }

  /**
   * The segments&#39;s lowest elevation, in meters
   * @return elevationLow
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ELEVATION_LOW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getElevationLow() {
    return elevationLow;
  }


  @JsonProperty(value = JSON_PROPERTY_ELEVATION_LOW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setElevationLow(@jakarta.annotation.Nullable Float elevationLow) {
    this.elevationLow = elevationLow;
  }

  public SummarySegment startLatlng(@jakarta.annotation.Nullable List<Float> startLatlng) {
    
    this.startLatlng = startLatlng;
    return this;
  }

  public SummarySegment addStartLatlngItem(Float startLatlngItem) {
    if (this.startLatlng == null) {
      this.startLatlng = new ArrayList<>();
    }
    this.startLatlng.add(startLatlngItem);
    return this;
  }

  /**
   * A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers.
   * @return startLatlng
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_START_LATLNG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Float> getStartLatlng() {
    return startLatlng;
  }


  @JsonProperty(value = JSON_PROPERTY_START_LATLNG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartLatlng(@jakarta.annotation.Nullable List<Float> startLatlng) {
    this.startLatlng = startLatlng;
  }

  public SummarySegment endLatlng(@jakarta.annotation.Nullable List<Float> endLatlng) {
    
    this.endLatlng = endLatlng;
    return this;
  }

  public SummarySegment addEndLatlngItem(Float endLatlngItem) {
    if (this.endLatlng == null) {
      this.endLatlng = new ArrayList<>();
    }
    this.endLatlng.add(endLatlngItem);
    return this;
  }

  /**
   * A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers.
   * @return endLatlng
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_END_LATLNG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Float> getEndLatlng() {
    return endLatlng;
  }


  @JsonProperty(value = JSON_PROPERTY_END_LATLNG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndLatlng(@jakarta.annotation.Nullable List<Float> endLatlng) {
    this.endLatlng = endLatlng;
  }

  public SummarySegment climbCategory(@jakarta.annotation.Nullable Integer climbCategory) {
    
    this.climbCategory = climbCategory;
    return this;
  }

  /**
   * The category of the climb [0, 5]. Higher is harder ie. 5 is Hors catégorie, 0 is uncategorized in climb_category.
   * @return climbCategory
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CLIMB_CATEGORY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getClimbCategory() {
    return climbCategory;
  }


  @JsonProperty(value = JSON_PROPERTY_CLIMB_CATEGORY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClimbCategory(@jakarta.annotation.Nullable Integer climbCategory) {
    this.climbCategory = climbCategory;
  }

  public SummarySegment city(@jakarta.annotation.Nullable String city) {
    
    this.city = city;
    return this;
  }

  /**
   * The segments&#39;s city.
   * @return city
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCity() {
    return city;
  }


  @JsonProperty(value = JSON_PROPERTY_CITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCity(@jakarta.annotation.Nullable String city) {
    this.city = city;
  }

  public SummarySegment state(@jakarta.annotation.Nullable String state) {
    
    this.state = state;
    return this;
  }

  /**
   * The segments&#39;s state or geographical region.
   * @return state
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getState() {
    return state;
  }


  @JsonProperty(value = JSON_PROPERTY_STATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setState(@jakarta.annotation.Nullable String state) {
    this.state = state;
  }

  public SummarySegment country(@jakarta.annotation.Nullable String country) {
    
    this.country = country;
    return this;
  }

  /**
   * The segment&#39;s country.
   * @return country
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COUNTRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCountry() {
    return country;
  }


  @JsonProperty(value = JSON_PROPERTY_COUNTRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountry(@jakarta.annotation.Nullable String country) {
    this.country = country;
  }

  public SummarySegment _private(@jakarta.annotation.Nullable Boolean _private) {
    
    this._private = _private;
    return this;
  }

  /**
   * Whether this segment is private.
   * @return _private
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRIVATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPrivate() {
    return _private;
  }


  @JsonProperty(value = JSON_PROPERTY_PRIVATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrivate(@jakarta.annotation.Nullable Boolean _private) {
    this._private = _private;
  }

  public SummarySegment athletePrEffort(@jakarta.annotation.Nullable SummaryPRSegmentEffort athletePrEffort) {
    
    this.athletePrEffort = athletePrEffort;
    return this;
  }

  /**
   * Get athletePrEffort
   * @return athletePrEffort
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ATHLETE_PR_EFFORT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SummaryPRSegmentEffort getAthletePrEffort() {
    return athletePrEffort;
  }


  @JsonProperty(value = JSON_PROPERTY_ATHLETE_PR_EFFORT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAthletePrEffort(@jakarta.annotation.Nullable SummaryPRSegmentEffort athletePrEffort) {
    this.athletePrEffort = athletePrEffort;
  }

  public SummarySegment athleteSegmentStats(@jakarta.annotation.Nullable SummarySegmentEffort athleteSegmentStats) {
    
    this.athleteSegmentStats = athleteSegmentStats;
    return this;
  }

  /**
   * Get athleteSegmentStats
   * @return athleteSegmentStats
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ATHLETE_SEGMENT_STATS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SummarySegmentEffort getAthleteSegmentStats() {
    return athleteSegmentStats;
  }


  @JsonProperty(value = JSON_PROPERTY_ATHLETE_SEGMENT_STATS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAthleteSegmentStats(@jakarta.annotation.Nullable SummarySegmentEffort athleteSegmentStats) {
    this.athleteSegmentStats = athleteSegmentStats;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SummarySegment summarySegment = (SummarySegment) o;
    return Objects.equals(this.id, summarySegment.id) &&
        Objects.equals(this.name, summarySegment.name) &&
        Objects.equals(this.activityType, summarySegment.activityType) &&
        Objects.equals(this.distance, summarySegment.distance) &&
        Objects.equals(this.averageGrade, summarySegment.averageGrade) &&
        Objects.equals(this.maximumGrade, summarySegment.maximumGrade) &&
        Objects.equals(this.elevationHigh, summarySegment.elevationHigh) &&
        Objects.equals(this.elevationLow, summarySegment.elevationLow) &&
        Objects.equals(this.startLatlng, summarySegment.startLatlng) &&
        Objects.equals(this.endLatlng, summarySegment.endLatlng) &&
        Objects.equals(this.climbCategory, summarySegment.climbCategory) &&
        Objects.equals(this.city, summarySegment.city) &&
        Objects.equals(this.state, summarySegment.state) &&
        Objects.equals(this.country, summarySegment.country) &&
        Objects.equals(this._private, summarySegment._private) &&
        Objects.equals(this.athletePrEffort, summarySegment.athletePrEffort) &&
        Objects.equals(this.athleteSegmentStats, summarySegment.athleteSegmentStats);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, activityType, distance, averageGrade, maximumGrade, elevationHigh, elevationLow, startLatlng, endLatlng, climbCategory, city, state, country, _private, athletePrEffort, athleteSegmentStats);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SummarySegment {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    activityType: ").append(toIndentedString(activityType)).append("\n");
    sb.append("    distance: ").append(toIndentedString(distance)).append("\n");
    sb.append("    averageGrade: ").append(toIndentedString(averageGrade)).append("\n");
    sb.append("    maximumGrade: ").append(toIndentedString(maximumGrade)).append("\n");
    sb.append("    elevationHigh: ").append(toIndentedString(elevationHigh)).append("\n");
    sb.append("    elevationLow: ").append(toIndentedString(elevationLow)).append("\n");
    sb.append("    startLatlng: ").append(toIndentedString(startLatlng)).append("\n");
    sb.append("    endLatlng: ").append(toIndentedString(endLatlng)).append("\n");
    sb.append("    climbCategory: ").append(toIndentedString(climbCategory)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    _private: ").append(toIndentedString(_private)).append("\n");
    sb.append("    athletePrEffort: ").append(toIndentedString(athletePrEffort)).append("\n");
    sb.append("    athleteSegmentStats: ").append(toIndentedString(athleteSegmentStats)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `name` to the URL query string
    if (getName() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sname%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `activity_type` to the URL query string
    if (getActivityType() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sactivity_type%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getActivityType()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `distance` to the URL query string
    if (getDistance() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sdistance%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDistance()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `average_grade` to the URL query string
    if (getAverageGrade() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%saverage_grade%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAverageGrade()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `maximum_grade` to the URL query string
    if (getMaximumGrade() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%smaximum_grade%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMaximumGrade()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `elevation_high` to the URL query string
    if (getElevationHigh() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%selevation_high%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getElevationHigh()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `elevation_low` to the URL query string
    if (getElevationLow() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%selevation_low%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getElevationLow()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `start_latlng` to the URL query string
    if (getStartLatlng() != null) {
      for (int i = 0; i < getStartLatlng().size(); i++) {
        try {
          joiner.add(String.format(Locale.ROOT, "%sstart_latlng%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
              URLEncoder.encode(String.valueOf(getStartLatlng().get(i)), "UTF-8").replaceAll("\\+", "%20")));
        } catch (UnsupportedEncodingException e) {
          // Should never happen, UTF-8 is always supported
          throw new RuntimeException(e);
        }
      }
    }

    // add `end_latlng` to the URL query string
    if (getEndLatlng() != null) {
      for (int i = 0; i < getEndLatlng().size(); i++) {
        try {
          joiner.add(String.format(Locale.ROOT, "%send_latlng%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
              URLEncoder.encode(String.valueOf(getEndLatlng().get(i)), "UTF-8").replaceAll("\\+", "%20")));
        } catch (UnsupportedEncodingException e) {
          // Should never happen, UTF-8 is always supported
          throw new RuntimeException(e);
        }
      }
    }

    // add `climb_category` to the URL query string
    if (getClimbCategory() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sclimb_category%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getClimbCategory()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `city` to the URL query string
    if (getCity() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%scity%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCity()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `state` to the URL query string
    if (getState() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sstate%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getState()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `country` to the URL query string
    if (getCountry() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%scountry%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCountry()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `private` to the URL query string
    if (getPrivate() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sprivate%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPrivate()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `athlete_pr_effort` to the URL query string
    if (getAthletePrEffort() != null) {
      joiner.add(getAthletePrEffort().toUrlQueryString(prefix + "athlete_pr_effort" + suffix));
    }

    // add `athlete_segment_stats` to the URL query string
    if (getAthleteSegmentStats() != null) {
      joiner.add(getAthleteSegmentStats().toUrlQueryString(prefix + "athlete_segment_stats" + suffix));
    }

    return joiner.toString();
  }

}

