/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gade.gps.strava.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * SummaryPRSegmentEffort
 */
@JsonPropertyOrder({
  SummaryPRSegmentEffort.JSON_PROPERTY_PR_ACTIVITY_ID,
  SummaryPRSegmentEffort.JSON_PROPERTY_PR_ELAPSED_TIME,
  SummaryPRSegmentEffort.JSON_PROPERTY_PR_DATE,
  SummaryPRSegmentEffort.JSON_PROPERTY_EFFORT_COUNT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class SummaryPRSegmentEffort {
  public static final String JSON_PROPERTY_PR_ACTIVITY_ID = "pr_activity_id";
  @jakarta.annotation.Nullable
  private Long prActivityId;

  public static final String JSON_PROPERTY_PR_ELAPSED_TIME = "pr_elapsed_time";
  @jakarta.annotation.Nullable
  private Integer prElapsedTime;

  public static final String JSON_PROPERTY_PR_DATE = "pr_date";
  @jakarta.annotation.Nullable
  private OffsetDateTime prDate;

  public static final String JSON_PROPERTY_EFFORT_COUNT = "effort_count";
  @jakarta.annotation.Nullable
  private Integer effortCount;

  public SummaryPRSegmentEffort() {
  }

  public SummaryPRSegmentEffort prActivityId(@jakarta.annotation.Nullable Long prActivityId) {
    
    this.prActivityId = prActivityId;
    return this;
  }

  /**
   * The unique identifier of the activity related to the PR effort.
   * @return prActivityId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PR_ACTIVITY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getPrActivityId() {
    return prActivityId;
  }


  @JsonProperty(value = JSON_PROPERTY_PR_ACTIVITY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrActivityId(@jakarta.annotation.Nullable Long prActivityId) {
    this.prActivityId = prActivityId;
  }

  public SummaryPRSegmentEffort prElapsedTime(@jakarta.annotation.Nullable Integer prElapsedTime) {
    
    this.prElapsedTime = prElapsedTime;
    return this;
  }

  /**
   * The elapsed time ot the PR effort.
   * @return prElapsedTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PR_ELAPSED_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPrElapsedTime() {
    return prElapsedTime;
  }


  @JsonProperty(value = JSON_PROPERTY_PR_ELAPSED_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrElapsedTime(@jakarta.annotation.Nullable Integer prElapsedTime) {
    this.prElapsedTime = prElapsedTime;
  }

  public SummaryPRSegmentEffort prDate(@jakarta.annotation.Nullable OffsetDateTime prDate) {
    
    this.prDate = prDate;
    return this;
  }

  /**
   * The time at which the PR effort was started.
   * @return prDate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PR_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getPrDate() {
    return prDate;
  }


  @JsonProperty(value = JSON_PROPERTY_PR_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrDate(@jakarta.annotation.Nullable OffsetDateTime prDate) {
    this.prDate = prDate;
  }

  public SummaryPRSegmentEffort effortCount(@jakarta.annotation.Nullable Integer effortCount) {
    
    this.effortCount = effortCount;
    return this;
  }

  /**
   * Number of efforts by the authenticated athlete on this segment.
   * @return effortCount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EFFORT_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getEffortCount() {
    return effortCount;
  }


  @JsonProperty(value = JSON_PROPERTY_EFFORT_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEffortCount(@jakarta.annotation.Nullable Integer effortCount) {
    this.effortCount = effortCount;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SummaryPRSegmentEffort summaryPRSegmentEffort = (SummaryPRSegmentEffort) o;
    return Objects.equals(this.prActivityId, summaryPRSegmentEffort.prActivityId) &&
        Objects.equals(this.prElapsedTime, summaryPRSegmentEffort.prElapsedTime) &&
        Objects.equals(this.prDate, summaryPRSegmentEffort.prDate) &&
        Objects.equals(this.effortCount, summaryPRSegmentEffort.effortCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(prActivityId, prElapsedTime, prDate, effortCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SummaryPRSegmentEffort {\n");
    sb.append("    prActivityId: ").append(toIndentedString(prActivityId)).append("\n");
    sb.append("    prElapsedTime: ").append(toIndentedString(prElapsedTime)).append("\n");
    sb.append("    prDate: ").append(toIndentedString(prDate)).append("\n");
    sb.append("    effortCount: ").append(toIndentedString(effortCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `pr_activity_id` to the URL query string
    if (getPrActivityId() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%spr_activity_id%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPrActivityId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `pr_elapsed_time` to the URL query string
    if (getPrElapsedTime() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%spr_elapsed_time%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPrElapsedTime()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `pr_date` to the URL query string
    if (getPrDate() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%spr_date%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPrDate()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `effort_count` to the URL query string
    if (getEffortCount() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%seffort_count%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getEffortCount()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

