/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gade.gps.strava.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.gade.gps.strava.client.model.ActivityType;
import com.gade.gps.strava.client.model.MetaAthlete;
import com.gade.gps.strava.client.model.PolylineMap;
import com.gade.gps.strava.client.model.SportType;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * SummaryActivity
 */
@JsonPropertyOrder({
  SummaryActivity.JSON_PROPERTY_ID,
  SummaryActivity.JSON_PROPERTY_EXTERNAL_ID,
  SummaryActivity.JSON_PROPERTY_UPLOAD_ID,
  SummaryActivity.JSON_PROPERTY_ATHLETE,
  SummaryActivity.JSON_PROPERTY_NAME,
  SummaryActivity.JSON_PROPERTY_DISTANCE,
  SummaryActivity.JSON_PROPERTY_MOVING_TIME,
  SummaryActivity.JSON_PROPERTY_ELAPSED_TIME,
  SummaryActivity.JSON_PROPERTY_TOTAL_ELEVATION_GAIN,
  SummaryActivity.JSON_PROPERTY_ELEV_HIGH,
  SummaryActivity.JSON_PROPERTY_ELEV_LOW,
  SummaryActivity.JSON_PROPERTY_TYPE,
  SummaryActivity.JSON_PROPERTY_SPORT_TYPE,
  SummaryActivity.JSON_PROPERTY_START_DATE,
  SummaryActivity.JSON_PROPERTY_START_DATE_LOCAL,
  SummaryActivity.JSON_PROPERTY_TIMEZONE,
  SummaryActivity.JSON_PROPERTY_START_LATLNG,
  SummaryActivity.JSON_PROPERTY_END_LATLNG,
  SummaryActivity.JSON_PROPERTY_ACHIEVEMENT_COUNT,
  SummaryActivity.JSON_PROPERTY_KUDOS_COUNT,
  SummaryActivity.JSON_PROPERTY_COMMENT_COUNT,
  SummaryActivity.JSON_PROPERTY_ATHLETE_COUNT,
  SummaryActivity.JSON_PROPERTY_PHOTO_COUNT,
  SummaryActivity.JSON_PROPERTY_TOTAL_PHOTO_COUNT,
  SummaryActivity.JSON_PROPERTY_MAP,
  SummaryActivity.JSON_PROPERTY_DEVICE_NAME,
  SummaryActivity.JSON_PROPERTY_TRAINER,
  SummaryActivity.JSON_PROPERTY_COMMUTE,
  SummaryActivity.JSON_PROPERTY_MANUAL,
  SummaryActivity.JSON_PROPERTY_PRIVATE,
  SummaryActivity.JSON_PROPERTY_FLAGGED,
  SummaryActivity.JSON_PROPERTY_WORKOUT_TYPE,
  SummaryActivity.JSON_PROPERTY_UPLOAD_ID_STR,
  SummaryActivity.JSON_PROPERTY_AVERAGE_SPEED,
  SummaryActivity.JSON_PROPERTY_MAX_SPEED,
  SummaryActivity.JSON_PROPERTY_HAS_KUDOED,
  SummaryActivity.JSON_PROPERTY_HIDE_FROM_HOME,
  SummaryActivity.JSON_PROPERTY_GEAR_ID,
  SummaryActivity.JSON_PROPERTY_KILOJOULES,
  SummaryActivity.JSON_PROPERTY_AVERAGE_WATTS,
  SummaryActivity.JSON_PROPERTY_DEVICE_WATTS,
  SummaryActivity.JSON_PROPERTY_MAX_WATTS,
  SummaryActivity.JSON_PROPERTY_WEIGHTED_AVERAGE_WATTS,
  SummaryActivity.JSON_PROPERTY_AVERAGE_HEARTRATE,
  SummaryActivity.JSON_PROPERTY_AVERAGE_CADENCE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class SummaryActivity {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_EXTERNAL_ID = "external_id";
  @jakarta.annotation.Nullable
  private String externalId;

  public static final String JSON_PROPERTY_UPLOAD_ID = "upload_id";
  @jakarta.annotation.Nullable
  private Long uploadId;

  public static final String JSON_PROPERTY_ATHLETE = "athlete";
  @jakarta.annotation.Nullable
  private MetaAthlete athlete;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_DISTANCE = "distance";
  @jakarta.annotation.Nullable
  private Float distance;

  public static final String JSON_PROPERTY_MOVING_TIME = "moving_time";
  @jakarta.annotation.Nullable
  private Integer movingTime;

  public static final String JSON_PROPERTY_ELAPSED_TIME = "elapsed_time";
  @jakarta.annotation.Nullable
  private Integer elapsedTime;

  public static final String JSON_PROPERTY_TOTAL_ELEVATION_GAIN = "total_elevation_gain";
  @jakarta.annotation.Nullable
  private Float totalElevationGain;

  public static final String JSON_PROPERTY_ELEV_HIGH = "elev_high";
  @jakarta.annotation.Nullable
  private Float elevHigh;

  public static final String JSON_PROPERTY_ELEV_LOW = "elev_low";
  @jakarta.annotation.Nullable
  private Float elevLow;

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private ActivityType type;

  public static final String JSON_PROPERTY_SPORT_TYPE = "sport_type";
  @jakarta.annotation.Nullable
  private SportType sportType;

  public static final String JSON_PROPERTY_START_DATE = "start_date";
  @jakarta.annotation.Nullable
  private OffsetDateTime startDate;

  public static final String JSON_PROPERTY_START_DATE_LOCAL = "start_date_local";
  @jakarta.annotation.Nullable
  private OffsetDateTime startDateLocal;

  public static final String JSON_PROPERTY_TIMEZONE = "timezone";
  @jakarta.annotation.Nullable
  private String timezone;

  public static final String JSON_PROPERTY_START_LATLNG = "start_latlng";
  @jakarta.annotation.Nullable
  private List<Float> startLatlng = new ArrayList<>();

  public static final String JSON_PROPERTY_END_LATLNG = "end_latlng";
  @jakarta.annotation.Nullable
  private List<Float> endLatlng = new ArrayList<>();

  public static final String JSON_PROPERTY_ACHIEVEMENT_COUNT = "achievement_count";
  @jakarta.annotation.Nullable
  private Integer achievementCount;

  public static final String JSON_PROPERTY_KUDOS_COUNT = "kudos_count";
  @jakarta.annotation.Nullable
  private Integer kudosCount;

  public static final String JSON_PROPERTY_COMMENT_COUNT = "comment_count";
  @jakarta.annotation.Nullable
  private Integer commentCount;

  public static final String JSON_PROPERTY_ATHLETE_COUNT = "athlete_count";
  @jakarta.annotation.Nullable
  private Integer athleteCount;

  public static final String JSON_PROPERTY_PHOTO_COUNT = "photo_count";
  @jakarta.annotation.Nullable
  private Integer photoCount;

  public static final String JSON_PROPERTY_TOTAL_PHOTO_COUNT = "total_photo_count";
  @jakarta.annotation.Nullable
  private Integer totalPhotoCount;

  public static final String JSON_PROPERTY_MAP = "map";
  @jakarta.annotation.Nullable
  private PolylineMap map;

  public static final String JSON_PROPERTY_DEVICE_NAME = "device_name";
  @jakarta.annotation.Nullable
  private String deviceName;

  public static final String JSON_PROPERTY_TRAINER = "trainer";
  @jakarta.annotation.Nullable
  private Boolean trainer;

  public static final String JSON_PROPERTY_COMMUTE = "commute";
  @jakarta.annotation.Nullable
  private Boolean commute;

  public static final String JSON_PROPERTY_MANUAL = "manual";
  @jakarta.annotation.Nullable
  private Boolean manual;

  public static final String JSON_PROPERTY_PRIVATE = "private";
  @jakarta.annotation.Nullable
  private Boolean _private;

  public static final String JSON_PROPERTY_FLAGGED = "flagged";
  @jakarta.annotation.Nullable
  private Boolean flagged;

  public static final String JSON_PROPERTY_WORKOUT_TYPE = "workout_type";
  @jakarta.annotation.Nullable
  private Integer workoutType;

  public static final String JSON_PROPERTY_UPLOAD_ID_STR = "upload_id_str";
  @jakarta.annotation.Nullable
  private String uploadIdStr;

  public static final String JSON_PROPERTY_AVERAGE_SPEED = "average_speed";
  @jakarta.annotation.Nullable
  private Float averageSpeed;

  public static final String JSON_PROPERTY_MAX_SPEED = "max_speed";
  @jakarta.annotation.Nullable
  private Float maxSpeed;

  public static final String JSON_PROPERTY_HAS_KUDOED = "has_kudoed";
  @jakarta.annotation.Nullable
  private Boolean hasKudoed;

  public static final String JSON_PROPERTY_HIDE_FROM_HOME = "hide_from_home";
  @jakarta.annotation.Nullable
  private Boolean hideFromHome;

  public static final String JSON_PROPERTY_GEAR_ID = "gear_id";
  @jakarta.annotation.Nullable
  private String gearId;

  public static final String JSON_PROPERTY_KILOJOULES = "kilojoules";
  @jakarta.annotation.Nullable
  private Float kilojoules;

  public static final String JSON_PROPERTY_AVERAGE_WATTS = "average_watts";
  @jakarta.annotation.Nullable
  private Float averageWatts;

  public static final String JSON_PROPERTY_DEVICE_WATTS = "device_watts";
  @jakarta.annotation.Nullable
  private Boolean deviceWatts;

  public static final String JSON_PROPERTY_MAX_WATTS = "max_watts";
  @jakarta.annotation.Nullable
  private Integer maxWatts;

  public static final String JSON_PROPERTY_WEIGHTED_AVERAGE_WATTS = "weighted_average_watts";
  @jakarta.annotation.Nullable
  private Integer weightedAverageWatts;

  public static final String JSON_PROPERTY_AVERAGE_HEARTRATE = "average_heartrate";
  @jakarta.annotation.Nullable
  private Float averageHeartrate;

  public static final String JSON_PROPERTY_AVERAGE_CADENCE = "average_cadence";
  @jakarta.annotation.Nullable
  private Float averageCadence;

  public SummaryActivity() {
  }

  public SummaryActivity id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * The unique identifier of the activity
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }

  public SummaryActivity externalId(@jakarta.annotation.Nullable String externalId) {
    
    this.externalId = externalId;
    return this;
  }

  /**
   * The identifier provided at upload time
   * @return externalId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXTERNAL_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExternalId() {
    return externalId;
  }


  @JsonProperty(value = JSON_PROPERTY_EXTERNAL_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExternalId(@jakarta.annotation.Nullable String externalId) {
    this.externalId = externalId;
  }

  public SummaryActivity uploadId(@jakarta.annotation.Nullable Long uploadId) {
    
    this.uploadId = uploadId;
    return this;
  }

  /**
   * The identifier of the upload that resulted in this activity
   * @return uploadId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPLOAD_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getUploadId() {
    return uploadId;
  }


  @JsonProperty(value = JSON_PROPERTY_UPLOAD_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUploadId(@jakarta.annotation.Nullable Long uploadId) {
    this.uploadId = uploadId;
  }

  public SummaryActivity athlete(@jakarta.annotation.Nullable MetaAthlete athlete) {
    
    this.athlete = athlete;
    return this;
  }

  /**
   * Get athlete
   * @return athlete
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ATHLETE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MetaAthlete getAthlete() {
    return athlete;
  }


  @JsonProperty(value = JSON_PROPERTY_ATHLETE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAthlete(@jakarta.annotation.Nullable MetaAthlete athlete) {
    this.athlete = athlete;
  }

  public SummaryActivity name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * The name of the activity
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public SummaryActivity distance(@jakarta.annotation.Nullable Float distance) {
    
    this.distance = distance;
    return this;
  }

  /**
   * The activity&#39;s distance, in meters
   * @return distance
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DISTANCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getDistance() {
    return distance;
  }


  @JsonProperty(value = JSON_PROPERTY_DISTANCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDistance(@jakarta.annotation.Nullable Float distance) {
    this.distance = distance;
  }

  public SummaryActivity movingTime(@jakarta.annotation.Nullable Integer movingTime) {
    
    this.movingTime = movingTime;
    return this;
  }

  /**
   * The activity&#39;s moving time, in seconds
   * @return movingTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MOVING_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMovingTime() {
    return movingTime;
  }


  @JsonProperty(value = JSON_PROPERTY_MOVING_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMovingTime(@jakarta.annotation.Nullable Integer movingTime) {
    this.movingTime = movingTime;
  }

  public SummaryActivity elapsedTime(@jakarta.annotation.Nullable Integer elapsedTime) {
    
    this.elapsedTime = elapsedTime;
    return this;
  }

  /**
   * The activity&#39;s elapsed time, in seconds
   * @return elapsedTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ELAPSED_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getElapsedTime() {
    return elapsedTime;
  }


  @JsonProperty(value = JSON_PROPERTY_ELAPSED_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setElapsedTime(@jakarta.annotation.Nullable Integer elapsedTime) {
    this.elapsedTime = elapsedTime;
  }

  public SummaryActivity totalElevationGain(@jakarta.annotation.Nullable Float totalElevationGain) {
    
    this.totalElevationGain = totalElevationGain;
    return this;
  }

  /**
   * The activity&#39;s total elevation gain.
   * @return totalElevationGain
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_ELEVATION_GAIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getTotalElevationGain() {
    return totalElevationGain;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_ELEVATION_GAIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalElevationGain(@jakarta.annotation.Nullable Float totalElevationGain) {
    this.totalElevationGain = totalElevationGain;
  }

  public SummaryActivity elevHigh(@jakarta.annotation.Nullable Float elevHigh) {
    
    this.elevHigh = elevHigh;
    return this;
  }

  /**
   * The activity&#39;s highest elevation, in meters
   * @return elevHigh
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ELEV_HIGH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getElevHigh() {
    return elevHigh;
  }


  @JsonProperty(value = JSON_PROPERTY_ELEV_HIGH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setElevHigh(@jakarta.annotation.Nullable Float elevHigh) {
    this.elevHigh = elevHigh;
  }

  public SummaryActivity elevLow(@jakarta.annotation.Nullable Float elevLow) {
    
    this.elevLow = elevLow;
    return this;
  }

  /**
   * The activity&#39;s lowest elevation, in meters
   * @return elevLow
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ELEV_LOW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getElevLow() {
    return elevLow;
  }


  @JsonProperty(value = JSON_PROPERTY_ELEV_LOW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setElevLow(@jakarta.annotation.Nullable Float elevLow) {
    this.elevLow = elevLow;
  }

  public SummaryActivity type(@jakarta.annotation.Nullable ActivityType type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ActivityType getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@jakarta.annotation.Nullable ActivityType type) {
    this.type = type;
  }

  public SummaryActivity sportType(@jakarta.annotation.Nullable SportType sportType) {
    
    this.sportType = sportType;
    return this;
  }

  /**
   * Get sportType
   * @return sportType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SPORT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SportType getSportType() {
    return sportType;
  }


  @JsonProperty(value = JSON_PROPERTY_SPORT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSportType(@jakarta.annotation.Nullable SportType sportType) {
    this.sportType = sportType;
  }

  public SummaryActivity startDate(@jakarta.annotation.Nullable OffsetDateTime startDate) {
    
    this.startDate = startDate;
    return this;
  }

  /**
   * The time at which the activity was started.
   * @return startDate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_START_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getStartDate() {
    return startDate;
  }


  @JsonProperty(value = JSON_PROPERTY_START_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartDate(@jakarta.annotation.Nullable OffsetDateTime startDate) {
    this.startDate = startDate;
  }

  public SummaryActivity startDateLocal(@jakarta.annotation.Nullable OffsetDateTime startDateLocal) {
    
    this.startDateLocal = startDateLocal;
    return this;
  }

  /**
   * The time at which the activity was started in the local timezone.
   * @return startDateLocal
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_START_DATE_LOCAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getStartDateLocal() {
    return startDateLocal;
  }


  @JsonProperty(value = JSON_PROPERTY_START_DATE_LOCAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartDateLocal(@jakarta.annotation.Nullable OffsetDateTime startDateLocal) {
    this.startDateLocal = startDateLocal;
  }

  public SummaryActivity timezone(@jakarta.annotation.Nullable String timezone) {
    
    this.timezone = timezone;
    return this;
  }

  /**
   * The timezone of the activity
   * @return timezone
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMEZONE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTimezone() {
    return timezone;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMEZONE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimezone(@jakarta.annotation.Nullable String timezone) {
    this.timezone = timezone;
  }

  public SummaryActivity startLatlng(@jakarta.annotation.Nullable List<Float> startLatlng) {
    
    this.startLatlng = startLatlng;
    return this;
  }

  public SummaryActivity addStartLatlngItem(Float startLatlngItem) {
    if (this.startLatlng == null) {
      this.startLatlng = new ArrayList<>();
    }
    this.startLatlng.add(startLatlngItem);
    return this;
  }

  /**
   * A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers.
   * @return startLatlng
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_START_LATLNG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Float> getStartLatlng() {
    return startLatlng;
  }


  @JsonProperty(value = JSON_PROPERTY_START_LATLNG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartLatlng(@jakarta.annotation.Nullable List<Float> startLatlng) {
    this.startLatlng = startLatlng;
  }

  public SummaryActivity endLatlng(@jakarta.annotation.Nullable List<Float> endLatlng) {
    
    this.endLatlng = endLatlng;
    return this;
  }

  public SummaryActivity addEndLatlngItem(Float endLatlngItem) {
    if (this.endLatlng == null) {
      this.endLatlng = new ArrayList<>();
    }
    this.endLatlng.add(endLatlngItem);
    return this;
  }

  /**
   * A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers.
   * @return endLatlng
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_END_LATLNG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Float> getEndLatlng() {
    return endLatlng;
  }


  @JsonProperty(value = JSON_PROPERTY_END_LATLNG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndLatlng(@jakarta.annotation.Nullable List<Float> endLatlng) {
    this.endLatlng = endLatlng;
  }

  public SummaryActivity achievementCount(@jakarta.annotation.Nullable Integer achievementCount) {
    
    this.achievementCount = achievementCount;
    return this;
  }

  /**
   * The number of achievements gained during this activity
   * @return achievementCount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACHIEVEMENT_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAchievementCount() {
    return achievementCount;
  }


  @JsonProperty(value = JSON_PROPERTY_ACHIEVEMENT_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAchievementCount(@jakarta.annotation.Nullable Integer achievementCount) {
    this.achievementCount = achievementCount;
  }

  public SummaryActivity kudosCount(@jakarta.annotation.Nullable Integer kudosCount) {
    
    this.kudosCount = kudosCount;
    return this;
  }

  /**
   * The number of kudos given for this activity
   * @return kudosCount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_KUDOS_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getKudosCount() {
    return kudosCount;
  }


  @JsonProperty(value = JSON_PROPERTY_KUDOS_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKudosCount(@jakarta.annotation.Nullable Integer kudosCount) {
    this.kudosCount = kudosCount;
  }

  public SummaryActivity commentCount(@jakarta.annotation.Nullable Integer commentCount) {
    
    this.commentCount = commentCount;
    return this;
  }

  /**
   * The number of comments for this activity
   * @return commentCount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMMENT_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCommentCount() {
    return commentCount;
  }


  @JsonProperty(value = JSON_PROPERTY_COMMENT_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommentCount(@jakarta.annotation.Nullable Integer commentCount) {
    this.commentCount = commentCount;
  }

  public SummaryActivity athleteCount(@jakarta.annotation.Nullable Integer athleteCount) {
    
    this.athleteCount = athleteCount;
    return this;
  }

  /**
   * The number of athletes for taking part in a group activity
   * minimum: 1
   * @return athleteCount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ATHLETE_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAthleteCount() {
    return athleteCount;
  }


  @JsonProperty(value = JSON_PROPERTY_ATHLETE_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAthleteCount(@jakarta.annotation.Nullable Integer athleteCount) {
    this.athleteCount = athleteCount;
  }

  public SummaryActivity photoCount(@jakarta.annotation.Nullable Integer photoCount) {
    
    this.photoCount = photoCount;
    return this;
  }

  /**
   * The number of Instagram photos for this activity
   * @return photoCount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PHOTO_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPhotoCount() {
    return photoCount;
  }


  @JsonProperty(value = JSON_PROPERTY_PHOTO_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhotoCount(@jakarta.annotation.Nullable Integer photoCount) {
    this.photoCount = photoCount;
  }

  public SummaryActivity totalPhotoCount(@jakarta.annotation.Nullable Integer totalPhotoCount) {
    
    this.totalPhotoCount = totalPhotoCount;
    return this;
  }

  /**
   * The number of Instagram and Strava photos for this activity
   * @return totalPhotoCount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_PHOTO_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTotalPhotoCount() {
    return totalPhotoCount;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_PHOTO_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalPhotoCount(@jakarta.annotation.Nullable Integer totalPhotoCount) {
    this.totalPhotoCount = totalPhotoCount;
  }

  public SummaryActivity map(@jakarta.annotation.Nullable PolylineMap map) {
    
    this.map = map;
    return this;
  }

  /**
   * Get map
   * @return map
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PolylineMap getMap() {
    return map;
  }


  @JsonProperty(value = JSON_PROPERTY_MAP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMap(@jakarta.annotation.Nullable PolylineMap map) {
    this.map = map;
  }

  public SummaryActivity deviceName(@jakarta.annotation.Nullable String deviceName) {
    
    this.deviceName = deviceName;
    return this;
  }

  /**
   * The name of the device used to record the activity
   * @return deviceName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEVICE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDeviceName() {
    return deviceName;
  }


  @JsonProperty(value = JSON_PROPERTY_DEVICE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeviceName(@jakarta.annotation.Nullable String deviceName) {
    this.deviceName = deviceName;
  }

  public SummaryActivity trainer(@jakarta.annotation.Nullable Boolean trainer) {
    
    this.trainer = trainer;
    return this;
  }

  /**
   * Whether this activity was recorded on a training machine
   * @return trainer
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRAINER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTrainer() {
    return trainer;
  }


  @JsonProperty(value = JSON_PROPERTY_TRAINER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrainer(@jakarta.annotation.Nullable Boolean trainer) {
    this.trainer = trainer;
  }

  public SummaryActivity commute(@jakarta.annotation.Nullable Boolean commute) {
    
    this.commute = commute;
    return this;
  }

  /**
   * Whether this activity is a commute
   * @return commute
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMMUTE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCommute() {
    return commute;
  }


  @JsonProperty(value = JSON_PROPERTY_COMMUTE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommute(@jakarta.annotation.Nullable Boolean commute) {
    this.commute = commute;
  }

  public SummaryActivity manual(@jakarta.annotation.Nullable Boolean manual) {
    
    this.manual = manual;
    return this;
  }

  /**
   * Whether this activity was created manually
   * @return manual
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MANUAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getManual() {
    return manual;
  }


  @JsonProperty(value = JSON_PROPERTY_MANUAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManual(@jakarta.annotation.Nullable Boolean manual) {
    this.manual = manual;
  }

  public SummaryActivity _private(@jakarta.annotation.Nullable Boolean _private) {
    
    this._private = _private;
    return this;
  }

  /**
   * Whether this activity is private
   * @return _private
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRIVATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPrivate() {
    return _private;
  }


  @JsonProperty(value = JSON_PROPERTY_PRIVATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrivate(@jakarta.annotation.Nullable Boolean _private) {
    this._private = _private;
  }

  public SummaryActivity flagged(@jakarta.annotation.Nullable Boolean flagged) {
    
    this.flagged = flagged;
    return this;
  }

  /**
   * Whether this activity is flagged
   * @return flagged
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FLAGGED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getFlagged() {
    return flagged;
  }


  @JsonProperty(value = JSON_PROPERTY_FLAGGED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFlagged(@jakarta.annotation.Nullable Boolean flagged) {
    this.flagged = flagged;
  }

  public SummaryActivity workoutType(@jakarta.annotation.Nullable Integer workoutType) {
    
    this.workoutType = workoutType;
    return this;
  }

  /**
   * The activity&#39;s workout type
   * @return workoutType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WORKOUT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getWorkoutType() {
    return workoutType;
  }


  @JsonProperty(value = JSON_PROPERTY_WORKOUT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWorkoutType(@jakarta.annotation.Nullable Integer workoutType) {
    this.workoutType = workoutType;
  }

  public SummaryActivity uploadIdStr(@jakarta.annotation.Nullable String uploadIdStr) {
    
    this.uploadIdStr = uploadIdStr;
    return this;
  }

  /**
   * The unique identifier of the upload in string format
   * @return uploadIdStr
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPLOAD_ID_STR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUploadIdStr() {
    return uploadIdStr;
  }


  @JsonProperty(value = JSON_PROPERTY_UPLOAD_ID_STR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUploadIdStr(@jakarta.annotation.Nullable String uploadIdStr) {
    this.uploadIdStr = uploadIdStr;
  }

  public SummaryActivity averageSpeed(@jakarta.annotation.Nullable Float averageSpeed) {
    
    this.averageSpeed = averageSpeed;
    return this;
  }

  /**
   * The activity&#39;s average speed, in meters per second
   * @return averageSpeed
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AVERAGE_SPEED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getAverageSpeed() {
    return averageSpeed;
  }


  @JsonProperty(value = JSON_PROPERTY_AVERAGE_SPEED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAverageSpeed(@jakarta.annotation.Nullable Float averageSpeed) {
    this.averageSpeed = averageSpeed;
  }

  public SummaryActivity maxSpeed(@jakarta.annotation.Nullable Float maxSpeed) {
    
    this.maxSpeed = maxSpeed;
    return this;
  }

  /**
   * The activity&#39;s max speed, in meters per second
   * @return maxSpeed
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAX_SPEED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getMaxSpeed() {
    return maxSpeed;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX_SPEED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxSpeed(@jakarta.annotation.Nullable Float maxSpeed) {
    this.maxSpeed = maxSpeed;
  }

  public SummaryActivity hasKudoed(@jakarta.annotation.Nullable Boolean hasKudoed) {
    
    this.hasKudoed = hasKudoed;
    return this;
  }

  /**
   * Whether the logged-in athlete has kudoed this activity
   * @return hasKudoed
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HAS_KUDOED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHasKudoed() {
    return hasKudoed;
  }


  @JsonProperty(value = JSON_PROPERTY_HAS_KUDOED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHasKudoed(@jakarta.annotation.Nullable Boolean hasKudoed) {
    this.hasKudoed = hasKudoed;
  }

  public SummaryActivity hideFromHome(@jakarta.annotation.Nullable Boolean hideFromHome) {
    
    this.hideFromHome = hideFromHome;
    return this;
  }

  /**
   * Whether the activity is muted
   * @return hideFromHome
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HIDE_FROM_HOME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHideFromHome() {
    return hideFromHome;
  }


  @JsonProperty(value = JSON_PROPERTY_HIDE_FROM_HOME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHideFromHome(@jakarta.annotation.Nullable Boolean hideFromHome) {
    this.hideFromHome = hideFromHome;
  }

  public SummaryActivity gearId(@jakarta.annotation.Nullable String gearId) {
    
    this.gearId = gearId;
    return this;
  }

  /**
   * The id of the gear for the activity
   * @return gearId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GEAR_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGearId() {
    return gearId;
  }


  @JsonProperty(value = JSON_PROPERTY_GEAR_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGearId(@jakarta.annotation.Nullable String gearId) {
    this.gearId = gearId;
  }

  public SummaryActivity kilojoules(@jakarta.annotation.Nullable Float kilojoules) {
    
    this.kilojoules = kilojoules;
    return this;
  }

  /**
   * The total work done in kilojoules during this activity. Rides only
   * @return kilojoules
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_KILOJOULES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getKilojoules() {
    return kilojoules;
  }


  @JsonProperty(value = JSON_PROPERTY_KILOJOULES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKilojoules(@jakarta.annotation.Nullable Float kilojoules) {
    this.kilojoules = kilojoules;
  }

  public SummaryActivity averageWatts(@jakarta.annotation.Nullable Float averageWatts) {
    
    this.averageWatts = averageWatts;
    return this;
  }

  /**
   * Average power output in watts during this activity. Rides only
   * @return averageWatts
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AVERAGE_WATTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getAverageWatts() {
    return averageWatts;
  }


  @JsonProperty(value = JSON_PROPERTY_AVERAGE_WATTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAverageWatts(@jakarta.annotation.Nullable Float averageWatts) {
    this.averageWatts = averageWatts;
  }

  public SummaryActivity deviceWatts(@jakarta.annotation.Nullable Boolean deviceWatts) {
    
    this.deviceWatts = deviceWatts;
    return this;
  }

  /**
   * Whether the watts are from a power meter, false if estimated
   * @return deviceWatts
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEVICE_WATTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDeviceWatts() {
    return deviceWatts;
  }


  @JsonProperty(value = JSON_PROPERTY_DEVICE_WATTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeviceWatts(@jakarta.annotation.Nullable Boolean deviceWatts) {
    this.deviceWatts = deviceWatts;
  }

  public SummaryActivity maxWatts(@jakarta.annotation.Nullable Integer maxWatts) {
    
    this.maxWatts = maxWatts;
    return this;
  }

  /**
   * Rides with power meter data only
   * @return maxWatts
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAX_WATTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMaxWatts() {
    return maxWatts;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX_WATTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxWatts(@jakarta.annotation.Nullable Integer maxWatts) {
    this.maxWatts = maxWatts;
  }

  public SummaryActivity weightedAverageWatts(@jakarta.annotation.Nullable Integer weightedAverageWatts) {
    
    this.weightedAverageWatts = weightedAverageWatts;
    return this;
  }

  /**
   * Similar to Normalized Power. Rides with power meter data only
   * @return weightedAverageWatts
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WEIGHTED_AVERAGE_WATTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getWeightedAverageWatts() {
    return weightedAverageWatts;
  }


  @JsonProperty(value = JSON_PROPERTY_WEIGHTED_AVERAGE_WATTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWeightedAverageWatts(@jakarta.annotation.Nullable Integer weightedAverageWatts) {
    this.weightedAverageWatts = weightedAverageWatts;
  }

  public SummaryActivity averageHeartrate(@jakarta.annotation.Nullable Float averageHeartrate) {
    
    this.averageHeartrate = averageHeartrate;
    return this;
  }

  /**
   * Average HR
   * @return averageHeartrate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AVERAGE_HEARTRATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getAverageHeartrate() {
    return averageHeartrate;
  }


  @JsonProperty(value = JSON_PROPERTY_AVERAGE_HEARTRATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAverageHeartrate(@jakarta.annotation.Nullable Float averageHeartrate) {
    this.averageHeartrate = averageHeartrate;
  }

  public SummaryActivity averageCadence(@jakarta.annotation.Nullable Float averageCadence) {
    
    this.averageCadence = averageCadence;
    return this;
  }

  /**
   * Average cadence
   * @return averageCadence
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AVERAGE_CADENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getAverageCadence() {
    return averageCadence;
  }


  @JsonProperty(value = JSON_PROPERTY_AVERAGE_CADENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAverageCadence(@jakarta.annotation.Nullable Float averageCadence) {
    this.averageCadence = averageCadence;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SummaryActivity summaryActivity = (SummaryActivity) o;
    return Objects.equals(this.id, summaryActivity.id) &&
        Objects.equals(this.externalId, summaryActivity.externalId) &&
        Objects.equals(this.uploadId, summaryActivity.uploadId) &&
        Objects.equals(this.athlete, summaryActivity.athlete) &&
        Objects.equals(this.name, summaryActivity.name) &&
        Objects.equals(this.distance, summaryActivity.distance) &&
        Objects.equals(this.movingTime, summaryActivity.movingTime) &&
        Objects.equals(this.elapsedTime, summaryActivity.elapsedTime) &&
        Objects.equals(this.totalElevationGain, summaryActivity.totalElevationGain) &&
        Objects.equals(this.elevHigh, summaryActivity.elevHigh) &&
        Objects.equals(this.elevLow, summaryActivity.elevLow) &&
        Objects.equals(this.type, summaryActivity.type) &&
        Objects.equals(this.sportType, summaryActivity.sportType) &&
        Objects.equals(this.startDate, summaryActivity.startDate) &&
        Objects.equals(this.startDateLocal, summaryActivity.startDateLocal) &&
        Objects.equals(this.timezone, summaryActivity.timezone) &&
        Objects.equals(this.startLatlng, summaryActivity.startLatlng) &&
        Objects.equals(this.endLatlng, summaryActivity.endLatlng) &&
        Objects.equals(this.achievementCount, summaryActivity.achievementCount) &&
        Objects.equals(this.kudosCount, summaryActivity.kudosCount) &&
        Objects.equals(this.commentCount, summaryActivity.commentCount) &&
        Objects.equals(this.athleteCount, summaryActivity.athleteCount) &&
        Objects.equals(this.photoCount, summaryActivity.photoCount) &&
        Objects.equals(this.totalPhotoCount, summaryActivity.totalPhotoCount) &&
        Objects.equals(this.map, summaryActivity.map) &&
        Objects.equals(this.deviceName, summaryActivity.deviceName) &&
        Objects.equals(this.trainer, summaryActivity.trainer) &&
        Objects.equals(this.commute, summaryActivity.commute) &&
        Objects.equals(this.manual, summaryActivity.manual) &&
        Objects.equals(this._private, summaryActivity._private) &&
        Objects.equals(this.flagged, summaryActivity.flagged) &&
        Objects.equals(this.workoutType, summaryActivity.workoutType) &&
        Objects.equals(this.uploadIdStr, summaryActivity.uploadIdStr) &&
        Objects.equals(this.averageSpeed, summaryActivity.averageSpeed) &&
        Objects.equals(this.maxSpeed, summaryActivity.maxSpeed) &&
        Objects.equals(this.hasKudoed, summaryActivity.hasKudoed) &&
        Objects.equals(this.hideFromHome, summaryActivity.hideFromHome) &&
        Objects.equals(this.gearId, summaryActivity.gearId) &&
        Objects.equals(this.kilojoules, summaryActivity.kilojoules) &&
        Objects.equals(this.averageWatts, summaryActivity.averageWatts) &&
        Objects.equals(this.deviceWatts, summaryActivity.deviceWatts) &&
        Objects.equals(this.maxWatts, summaryActivity.maxWatts) &&
        Objects.equals(this.weightedAverageWatts, summaryActivity.weightedAverageWatts) &&
        Objects.equals(this.averageHeartrate, summaryActivity.averageHeartrate) &&
        Objects.equals(this.averageCadence, summaryActivity.averageCadence);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, externalId, uploadId, athlete, name, distance, movingTime, elapsedTime, totalElevationGain, elevHigh, elevLow, type, sportType, startDate, startDateLocal, timezone, startLatlng, endLatlng, achievementCount, kudosCount, commentCount, athleteCount, photoCount, totalPhotoCount, map, deviceName, trainer, commute, manual, _private, flagged, workoutType, uploadIdStr, averageSpeed, maxSpeed, hasKudoed, hideFromHome, gearId, kilojoules, averageWatts, deviceWatts, maxWatts, weightedAverageWatts, averageHeartrate, averageCadence);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SummaryActivity {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    uploadId: ").append(toIndentedString(uploadId)).append("\n");
    sb.append("    athlete: ").append(toIndentedString(athlete)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    distance: ").append(toIndentedString(distance)).append("\n");
    sb.append("    movingTime: ").append(toIndentedString(movingTime)).append("\n");
    sb.append("    elapsedTime: ").append(toIndentedString(elapsedTime)).append("\n");
    sb.append("    totalElevationGain: ").append(toIndentedString(totalElevationGain)).append("\n");
    sb.append("    elevHigh: ").append(toIndentedString(elevHigh)).append("\n");
    sb.append("    elevLow: ").append(toIndentedString(elevLow)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    sportType: ").append(toIndentedString(sportType)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    startDateLocal: ").append(toIndentedString(startDateLocal)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    startLatlng: ").append(toIndentedString(startLatlng)).append("\n");
    sb.append("    endLatlng: ").append(toIndentedString(endLatlng)).append("\n");
    sb.append("    achievementCount: ").append(toIndentedString(achievementCount)).append("\n");
    sb.append("    kudosCount: ").append(toIndentedString(kudosCount)).append("\n");
    sb.append("    commentCount: ").append(toIndentedString(commentCount)).append("\n");
    sb.append("    athleteCount: ").append(toIndentedString(athleteCount)).append("\n");
    sb.append("    photoCount: ").append(toIndentedString(photoCount)).append("\n");
    sb.append("    totalPhotoCount: ").append(toIndentedString(totalPhotoCount)).append("\n");
    sb.append("    map: ").append(toIndentedString(map)).append("\n");
    sb.append("    deviceName: ").append(toIndentedString(deviceName)).append("\n");
    sb.append("    trainer: ").append(toIndentedString(trainer)).append("\n");
    sb.append("    commute: ").append(toIndentedString(commute)).append("\n");
    sb.append("    manual: ").append(toIndentedString(manual)).append("\n");
    sb.append("    _private: ").append(toIndentedString(_private)).append("\n");
    sb.append("    flagged: ").append(toIndentedString(flagged)).append("\n");
    sb.append("    workoutType: ").append(toIndentedString(workoutType)).append("\n");
    sb.append("    uploadIdStr: ").append(toIndentedString(uploadIdStr)).append("\n");
    sb.append("    averageSpeed: ").append(toIndentedString(averageSpeed)).append("\n");
    sb.append("    maxSpeed: ").append(toIndentedString(maxSpeed)).append("\n");
    sb.append("    hasKudoed: ").append(toIndentedString(hasKudoed)).append("\n");
    sb.append("    hideFromHome: ").append(toIndentedString(hideFromHome)).append("\n");
    sb.append("    gearId: ").append(toIndentedString(gearId)).append("\n");
    sb.append("    kilojoules: ").append(toIndentedString(kilojoules)).append("\n");
    sb.append("    averageWatts: ").append(toIndentedString(averageWatts)).append("\n");
    sb.append("    deviceWatts: ").append(toIndentedString(deviceWatts)).append("\n");
    sb.append("    maxWatts: ").append(toIndentedString(maxWatts)).append("\n");
    sb.append("    weightedAverageWatts: ").append(toIndentedString(weightedAverageWatts)).append("\n");
    sb.append("    averageHeartrate: ").append(toIndentedString(averageHeartrate)).append("\n");
    sb.append("    averageCadence: ").append(toIndentedString(averageCadence)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `external_id` to the URL query string
    if (getExternalId() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sexternal_id%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getExternalId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `upload_id` to the URL query string
    if (getUploadId() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%supload_id%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getUploadId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `athlete` to the URL query string
    if (getAthlete() != null) {
      joiner.add(getAthlete().toUrlQueryString(prefix + "athlete" + suffix));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sname%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `distance` to the URL query string
    if (getDistance() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sdistance%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDistance()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `moving_time` to the URL query string
    if (getMovingTime() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%smoving_time%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMovingTime()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `elapsed_time` to the URL query string
    if (getElapsedTime() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%selapsed_time%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getElapsedTime()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `total_elevation_gain` to the URL query string
    if (getTotalElevationGain() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%stotal_elevation_gain%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTotalElevationGain()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `elev_high` to the URL query string
    if (getElevHigh() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%selev_high%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getElevHigh()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `elev_low` to the URL query string
    if (getElevLow() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%selev_low%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getElevLow()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `type` to the URL query string
    if (getType() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%stype%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getType()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `sport_type` to the URL query string
    if (getSportType() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%ssport_type%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSportType()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `start_date` to the URL query string
    if (getStartDate() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sstart_date%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getStartDate()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `start_date_local` to the URL query string
    if (getStartDateLocal() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sstart_date_local%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getStartDateLocal()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `timezone` to the URL query string
    if (getTimezone() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%stimezone%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTimezone()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `start_latlng` to the URL query string
    if (getStartLatlng() != null) {
      for (int i = 0; i < getStartLatlng().size(); i++) {
        try {
          joiner.add(String.format(Locale.ROOT, "%sstart_latlng%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
              URLEncoder.encode(String.valueOf(getStartLatlng().get(i)), "UTF-8").replaceAll("\\+", "%20")));
        } catch (UnsupportedEncodingException e) {
          // Should never happen, UTF-8 is always supported
          throw new RuntimeException(e);
        }
      }
    }

    // add `end_latlng` to the URL query string
    if (getEndLatlng() != null) {
      for (int i = 0; i < getEndLatlng().size(); i++) {
        try {
          joiner.add(String.format(Locale.ROOT, "%send_latlng%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
              URLEncoder.encode(String.valueOf(getEndLatlng().get(i)), "UTF-8").replaceAll("\\+", "%20")));
        } catch (UnsupportedEncodingException e) {
          // Should never happen, UTF-8 is always supported
          throw new RuntimeException(e);
        }
      }
    }

    // add `achievement_count` to the URL query string
    if (getAchievementCount() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sachievement_count%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAchievementCount()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `kudos_count` to the URL query string
    if (getKudosCount() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%skudos_count%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getKudosCount()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `comment_count` to the URL query string
    if (getCommentCount() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%scomment_count%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCommentCount()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `athlete_count` to the URL query string
    if (getAthleteCount() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sathlete_count%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAthleteCount()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `photo_count` to the URL query string
    if (getPhotoCount() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sphoto_count%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPhotoCount()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `total_photo_count` to the URL query string
    if (getTotalPhotoCount() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%stotal_photo_count%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTotalPhotoCount()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `map` to the URL query string
    if (getMap() != null) {
      joiner.add(getMap().toUrlQueryString(prefix + "map" + suffix));
    }

    // add `device_name` to the URL query string
    if (getDeviceName() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sdevice_name%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDeviceName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `trainer` to the URL query string
    if (getTrainer() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%strainer%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTrainer()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `commute` to the URL query string
    if (getCommute() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%scommute%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCommute()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `manual` to the URL query string
    if (getManual() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%smanual%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getManual()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `private` to the URL query string
    if (getPrivate() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sprivate%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPrivate()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `flagged` to the URL query string
    if (getFlagged() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sflagged%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getFlagged()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `workout_type` to the URL query string
    if (getWorkoutType() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sworkout_type%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getWorkoutType()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `upload_id_str` to the URL query string
    if (getUploadIdStr() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%supload_id_str%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getUploadIdStr()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `average_speed` to the URL query string
    if (getAverageSpeed() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%saverage_speed%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAverageSpeed()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `max_speed` to the URL query string
    if (getMaxSpeed() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%smax_speed%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMaxSpeed()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `has_kudoed` to the URL query string
    if (getHasKudoed() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%shas_kudoed%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getHasKudoed()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `hide_from_home` to the URL query string
    if (getHideFromHome() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%shide_from_home%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getHideFromHome()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `gear_id` to the URL query string
    if (getGearId() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sgear_id%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getGearId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `kilojoules` to the URL query string
    if (getKilojoules() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%skilojoules%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getKilojoules()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `average_watts` to the URL query string
    if (getAverageWatts() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%saverage_watts%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAverageWatts()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `device_watts` to the URL query string
    if (getDeviceWatts() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sdevice_watts%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDeviceWatts()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `max_watts` to the URL query string
    if (getMaxWatts() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%smax_watts%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMaxWatts()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `weighted_average_watts` to the URL query string
    if (getWeightedAverageWatts() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sweighted_average_watts%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getWeightedAverageWatts()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `average_heartrate` to the URL query string
    if (getAverageHeartrate() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%saverage_heartrate%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAverageHeartrate()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `average_cadence` to the URL query string
    if (getAverageCadence() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%saverage_cadence%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAverageCadence()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

