/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gade.gps.strava.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.gade.gps.strava.client.model.ActivityType;
import com.gade.gps.strava.client.model.SportType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * UpdatableActivity
 */
@JsonPropertyOrder({
  UpdatableActivity.JSON_PROPERTY_COMMUTE,
  UpdatableActivity.JSON_PROPERTY_TRAINER,
  UpdatableActivity.JSON_PROPERTY_HIDE_FROM_HOME,
  UpdatableActivity.JSON_PROPERTY_DESCRIPTION,
  UpdatableActivity.JSON_PROPERTY_NAME,
  UpdatableActivity.JSON_PROPERTY_TYPE,
  UpdatableActivity.JSON_PROPERTY_SPORT_TYPE,
  UpdatableActivity.JSON_PROPERTY_GEAR_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class UpdatableActivity {
  public static final String JSON_PROPERTY_COMMUTE = "commute";
  @jakarta.annotation.Nullable
  private Boolean commute;

  public static final String JSON_PROPERTY_TRAINER = "trainer";
  @jakarta.annotation.Nullable
  private Boolean trainer;

  public static final String JSON_PROPERTY_HIDE_FROM_HOME = "hide_from_home";
  @jakarta.annotation.Nullable
  private Boolean hideFromHome;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private ActivityType type;

  public static final String JSON_PROPERTY_SPORT_TYPE = "sport_type";
  @jakarta.annotation.Nullable
  private SportType sportType;

  public static final String JSON_PROPERTY_GEAR_ID = "gear_id";
  @jakarta.annotation.Nullable
  private String gearId;

  public UpdatableActivity() {
  }

  public UpdatableActivity commute(@jakarta.annotation.Nullable Boolean commute) {
    
    this.commute = commute;
    return this;
  }

  /**
   * Whether this activity is a commute
   * @return commute
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMMUTE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCommute() {
    return commute;
  }


  @JsonProperty(value = JSON_PROPERTY_COMMUTE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommute(@jakarta.annotation.Nullable Boolean commute) {
    this.commute = commute;
  }

  public UpdatableActivity trainer(@jakarta.annotation.Nullable Boolean trainer) {
    
    this.trainer = trainer;
    return this;
  }

  /**
   * Whether this activity was recorded on a training machine
   * @return trainer
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRAINER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTrainer() {
    return trainer;
  }


  @JsonProperty(value = JSON_PROPERTY_TRAINER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrainer(@jakarta.annotation.Nullable Boolean trainer) {
    this.trainer = trainer;
  }

  public UpdatableActivity hideFromHome(@jakarta.annotation.Nullable Boolean hideFromHome) {
    
    this.hideFromHome = hideFromHome;
    return this;
  }

  /**
   * Whether this activity is muted
   * @return hideFromHome
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HIDE_FROM_HOME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHideFromHome() {
    return hideFromHome;
  }


  @JsonProperty(value = JSON_PROPERTY_HIDE_FROM_HOME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHideFromHome(@jakarta.annotation.Nullable Boolean hideFromHome) {
    this.hideFromHome = hideFromHome;
  }

  public UpdatableActivity description(@jakarta.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * The description of the activity
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = description;
  }

  public UpdatableActivity name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * The name of the activity
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public UpdatableActivity type(@jakarta.annotation.Nullable ActivityType type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ActivityType getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@jakarta.annotation.Nullable ActivityType type) {
    this.type = type;
  }

  public UpdatableActivity sportType(@jakarta.annotation.Nullable SportType sportType) {
    
    this.sportType = sportType;
    return this;
  }

  /**
   * Get sportType
   * @return sportType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SPORT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SportType getSportType() {
    return sportType;
  }


  @JsonProperty(value = JSON_PROPERTY_SPORT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSportType(@jakarta.annotation.Nullable SportType sportType) {
    this.sportType = sportType;
  }

  public UpdatableActivity gearId(@jakarta.annotation.Nullable String gearId) {
    
    this.gearId = gearId;
    return this;
  }

  /**
   * Identifier for the gear associated with the activity. ‘none’ clears gear from activity
   * @return gearId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GEAR_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGearId() {
    return gearId;
  }


  @JsonProperty(value = JSON_PROPERTY_GEAR_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGearId(@jakarta.annotation.Nullable String gearId) {
    this.gearId = gearId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdatableActivity updatableActivity = (UpdatableActivity) o;
    return Objects.equals(this.commute, updatableActivity.commute) &&
        Objects.equals(this.trainer, updatableActivity.trainer) &&
        Objects.equals(this.hideFromHome, updatableActivity.hideFromHome) &&
        Objects.equals(this.description, updatableActivity.description) &&
        Objects.equals(this.name, updatableActivity.name) &&
        Objects.equals(this.type, updatableActivity.type) &&
        Objects.equals(this.sportType, updatableActivity.sportType) &&
        Objects.equals(this.gearId, updatableActivity.gearId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commute, trainer, hideFromHome, description, name, type, sportType, gearId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdatableActivity {\n");
    sb.append("    commute: ").append(toIndentedString(commute)).append("\n");
    sb.append("    trainer: ").append(toIndentedString(trainer)).append("\n");
    sb.append("    hideFromHome: ").append(toIndentedString(hideFromHome)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    sportType: ").append(toIndentedString(sportType)).append("\n");
    sb.append("    gearId: ").append(toIndentedString(gearId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `commute` to the URL query string
    if (getCommute() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%scommute%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCommute()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `trainer` to the URL query string
    if (getTrainer() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%strainer%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTrainer()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `hide_from_home` to the URL query string
    if (getHideFromHome() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%shide_from_home%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getHideFromHome()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sdescription%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDescription()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `name` to the URL query string
    if (getName() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sname%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `type` to the URL query string
    if (getType() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%stype%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getType()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `sport_type` to the URL query string
    if (getSportType() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%ssport_type%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSportType()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `gear_id` to the URL query string
    if (getGearId() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sgear_id%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getGearId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

