/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gade.gps.strava.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.gade.gps.strava.client.model.HeartRateZoneRanges;
import com.gade.gps.strava.client.model.PowerZoneRanges;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * Zones
 */
@JsonPropertyOrder({
  Zones.JSON_PROPERTY_HEART_RATE,
  Zones.JSON_PROPERTY_POWER
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class Zones {
  public static final String JSON_PROPERTY_HEART_RATE = "heart_rate";
  @jakarta.annotation.Nullable
  private HeartRateZoneRanges heartRate;

  public static final String JSON_PROPERTY_POWER = "power";
  @jakarta.annotation.Nullable
  private PowerZoneRanges power;

  public Zones() {
  }

  public Zones heartRate(@jakarta.annotation.Nullable HeartRateZoneRanges heartRate) {
    
    this.heartRate = heartRate;
    return this;
  }

  /**
   * Get heartRate
   * @return heartRate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HEART_RATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public HeartRateZoneRanges getHeartRate() {
    return heartRate;
  }


  @JsonProperty(value = JSON_PROPERTY_HEART_RATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeartRate(@jakarta.annotation.Nullable HeartRateZoneRanges heartRate) {
    this.heartRate = heartRate;
  }

  public Zones power(@jakarta.annotation.Nullable PowerZoneRanges power) {
    
    this.power = power;
    return this;
  }

  /**
   * Get power
   * @return power
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_POWER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PowerZoneRanges getPower() {
    return power;
  }


  @JsonProperty(value = JSON_PROPERTY_POWER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPower(@jakarta.annotation.Nullable PowerZoneRanges power) {
    this.power = power;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Zones zones = (Zones) o;
    return Objects.equals(this.heartRate, zones.heartRate) &&
        Objects.equals(this.power, zones.power);
  }

  @Override
  public int hashCode() {
    return Objects.hash(heartRate, power);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Zones {\n");
    sb.append("    heartRate: ").append(toIndentedString(heartRate)).append("\n");
    sb.append("    power: ").append(toIndentedString(power)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `heart_rate` to the URL query string
    if (getHeartRate() != null) {
      joiner.add(getHeartRate().toUrlQueryString(prefix + "heart_rate" + suffix));
    }

    // add `power` to the URL query string
    if (getPower() != null) {
      joiner.add(getPower().toUrlQueryString(prefix + "power" + suffix));
    }

    return joiner.toString();
  }

}

